"""What a rendered file says about the thing that rendered it.

A sheet that names no generator cannot be traced back to the code that drew it,
which matters most exactly when it matters at all: a drawing that looks wrong is
a question about a version. Both backends now answer it -- the SVG in a comment
and a ``dc:creator``, the draw.io export in ``mxfile/@agent`` -- and this file
holds them to saying the same thing, in the right place, without breaking the
document to do it.

**Why it is not hidden.** White-on-white lettering in the drawing was considered
and rejected. Both formats are plain text, so a mark hidden from the eye is not
hidden from a reader of the file and buys nothing a comment does not; it is
removable in one edit, so it attributes a file but proves nothing about one; and
an invisible run of text in a controlled engineering document comes out on
select-all-copy and in any text extractor, into a client deliverable nobody
chose to put it in. Tamper-evidence, if it is ever wanted, is a hash over the
content and a different feature.
"""

import xml.etree.ElementTree as ET

import pytest

import pandid
from pandid import Flowsheet, units
from pandid.document import TitleBlock
from pandid.render import HOMEPAGE, generator

SVG_NS = "{http://www.w3.org/2000/svg}"
DC_NS = "{http://purl.org/dc/elements/1.1/}"


@pytest.fixture
def sheet() -> Flowsheet:
    """The smallest sheet that renders: a feed into a product."""
    fs = Flowsheet("Ammonia Loop Auto")
    feed = fs.add(units.Feed("Natural Gas"))
    product = fs.add(units.Product("Ammonia"))
    fs.connect(feed.outlet, product.inlet)
    return fs


# --- SVG ----------------------------------------------------------------------


def test_the_svg_names_the_generator_and_its_version(sheet):
    assert f"<!-- Generated by pandid {pandid.__version__}: {HOMEPAGE} -->" in sheet.to_svg()


def test_the_svg_carries_a_dublin_core_creator(sheet):
    root = ET.fromstring(sheet.to_svg())
    metadata = root.find(f"{SVG_NS}metadata")
    assert metadata is not None, "no <metadata> element"
    creator = metadata.find(f".//{DC_NS}creator")
    assert creator is not None and creator.text == generator()


def test_the_generator_comment_is_a_legal_xml_comment(sheet):
    """An XML comment may not contain ``--`` anywhere (XML 1.0 §2.5).

    The obvious prose separator for "pandid 0.1.2 -- https://..." is therefore
    the one thing that cannot go in it, and a sheet written with one is not an
    SVG at all -- it fails to parse before anything can draw it. Both halves are
    asserted: the document parses, and the comment carries no ``--``.
    """
    svg = sheet.to_svg()
    ET.fromstring(svg)  # raises ET.ParseError on a malformed comment
    comment = next(ln for ln in svg.split("\n") if ln.strip().startswith("<!-- Generated by"))
    assert "--" not in comment.strip()[4:-3]


def test_the_title_is_the_first_child_so_it_is_the_accessible_name(sheet):
    """``<title>`` is a tooltip in a browser and the document's name to a screen
    reader, and both look for it as the first child of ``<svg>``."""
    root = ET.fromstring(sheet.to_svg())
    assert root[0].tag == f"{SVG_NS}title"
    assert root[0].text == "Ammonia Loop Auto"


def test_the_title_is_the_one_the_sheet_is_issued_under(sheet):
    """A furnished sheet has two names: the flowsheet's, which is an identifier
    in the calling program, and the title block's, which is what is lettered on
    the drawing and what it is issued as. The second wins."""
    sheet.title_block = TitleBlock(title="Aromatics Recovery A100", date="2026-01-01")
    root = ET.fromstring(sheet.to_svg())
    assert root[0].text == "Aromatics Recovery A100"
    assert root.find(f"{SVG_NS}metadata/").find(f".//{DC_NS}title").text == (
        "Aromatics Recovery A100"
    )


def test_a_title_with_markup_in_it_does_not_break_the_document():
    fs = Flowsheet('Unit "A" <B> & C')
    fs.connect(fs.add(units.Feed("F")).outlet, fs.add(units.Product("P")).inlet)
    root = ET.fromstring(fs.to_svg())
    assert root[0].text == 'Unit "A" <B> & C'


def test_a_nameless_sheet_gets_no_empty_title():
    """An empty accessible name is worse than none: a screen reader announces a
    blank where it would otherwise fall back to something useful."""
    fs = Flowsheet("")
    fs.connect(fs.add(units.Feed("F")).outlet, fs.add(units.Product("P")).inlet)
    root = ET.fromstring(fs.to_svg())
    assert root[0].tag != f"{SVG_NS}title"


# --- draw.io ------------------------------------------------------------------


def test_the_drawio_agent_carries_the_version_and_the_host_does_not(sheet):
    """``agent`` is where draw.io writes what produced the file, so the version
    goes there; ``host`` names the application and stays a bare word."""
    root = ET.fromstring(sheet.to_drawio())
    assert root.get("host") == "pandid"
    assert root.get("agent") == f"pandid {pandid.__version__}"


# --- both ---------------------------------------------------------------------


def test_both_backends_read_the_version_when_they_render(sheet, monkeypatch):
    """Not at import.

    The version has to be read at render time or nothing can ever check it: a
    module constant captured on import is fixed before any test can reach it,
    and the check that a version bump leaves the goldens alone
    (``tests/test_golden.py``) depends on being able to set it and render.
    """
    monkeypatch.setattr(pandid, "__version__", "9.9.9-test")
    assert "<!-- Generated by pandid 9.9.9-test:" in sheet.to_svg()
    assert ET.fromstring(sheet.to_drawio()).get("agent") == "pandid 9.9.9-test"
