"""Hostile strings through every field a user controls, on both backends.

A spec file is untrusted input. It arrives by email, it is generated by
somebody else's tool, and the sheet drawn from it is opened in a
browser -- so a value that closes an SVG attribute and opens an
``onload=`` is script execution, and one that closes a tag is a document
that will not open at all.

This is a *property* test rather than a list of cases, because the
property is the whole point: for **every** field a user can fill and
**every** shape of hostile string, the rendered document must

* parse as XML;
* carry no attribute the value invented; and
* leave every ``url(#...)`` and ``href="#..."`` pointing at an id that
  exists in it.

The last one is not paranoia. An id is where escaping alone does not
save you: ``arrow_rgb(1,2,3)`` is a well-formed attribute value and not
a legal XML name, so a browser drops the ``<marker>`` and draws the line
with no arrowhead, while a PDF export -- which resolves the reference
itself -- still draws one. Nothing warns, and the two outputs disagree
about the drawing. :func:`~pandid.render.escape.ident` is the answer and
this file is what holds it.

Two fields are **refused** rather than escaped, and there is a test for
that too: ``color`` and ``dasharray`` are instructions to the renderer,
and an instruction it cannot read is not drawn oddly, it is dropped --
the line loses its stroke and disappears, or loses its dashes and reads
as a pipe. See :func:`pandid.streams.check_color`.

What is *not* checked here: no file path reaches either document, so
there is no path field to attack. ``test_no_file_path_reaches_the_sheet``
pins that rather than leaving it to be assumed.
"""

import re
import xml.etree.ElementTree as ET

import pytest

from pandid import Flowsheet, units as U
from pandid.document import (
    Annotation,
    Revision,
    TableBox,
    TitleBlock,
    equipment_list,
    legend,
    notes,
)
from pandid.render.escape import _NAME_CHARS, _UNSAFE_RUN, escaped, ident, writable
from pandid.render.svg import arrow_marker_id
from pandid.streams import check_color, check_dasharray

# The word a payload tries to smuggle in as an attribute name. Nothing
# the library writes contains it, so finding it on a parsed element is
# proof the value escaped its quotes rather than a guess about what a
# browser would have done with it.
INJECTED = "pandidinjected"

#: The shapes a hostile value comes in. Each one attacks a different
#: part of the serializer: the quote that ends an attribute, the angle
#: bracket that ends a tag, the ampersand that starts an entity, the
#: ``]]>`` that ends a section the document never opened, the byte XML
#: has no spelling for at all, and the sizes and alphabets that find a
#: buffer or an encoding assumption.
PAYLOADS = {
    "double quote": f'x" {INJECTED}="1',
    "single quote": f"x' {INJECTED}='1",
    "element": "<script>alert(1)</script>",
    "ampersand": "steam & water",
    "entity": "&lt; &amp; &#0;",
    "cdata close": "]]>",
    "comment": "<!-- x --> --",
    "control characters": "a\x00b\x01c\x1fd",
    "newlines": "one\ntwo\r\nthree",
    "non-ascii": "Cl₂ 中文 \U0001f525",
    "url reference": "url(#no-such-id)",
    "very long": "A" * 120,
}

#: Every field on this sheet a user fills in. One name per place a
#: string of theirs reaches a document; :func:`_plant` puts the payload
#: in exactly the one named and leaves the rest ordinary, so a failure
#: names the field that leaked.
FIELDS = (
    "flowsheet name",
    "unit name",
    "unit description",
    "off-page reference",
    "instrument letters",
    "loop number",
    "stream name",
    "line-number size",
    "line-number schedule",
    "line-number service",
    "line-number sequence",
    "line-number spec",
    "line-number insulation",
    "stream property name",
    "stream property value",
    "title",
    "subtitle",
    "drawing number",
    "project",
    "client",
    "company",
    "status",
    "sheet",
    "of sheets",
    "scale",
    "drawn by",
    "checked by",
    "approved by",
    "date",
    "revision",
    "note text",
    "legend entry",
    "annotation title",
    "table title",
    "table header",
    "table cell",
)

#: How the sheet is drawn while it is attacked. Two settings, because a
#: field only leaks through the furniture that draws it: the stream
#: table draws the properties, the zone border and the title strip draw
#: the title block, and a P&ID draws its joints where a PFD draws
#: arrowheads.
RENDERED = dict(
    border="zone", diagram="p&id", connections="flanged", show_stream_table=True, check=False
)

_URL = re.compile(r"url\(#([^)]*)\)")
_XLINK_HREF = "{http://www.w3.org/1999/xlink}href"


def _plant(payload: str, field: str) -> Flowsheet:
    """A small sheet with *payload* in *field* and nothing else.

    Every entry in :data:`FIELDS` appears here exactly once, so the
    table and the sheet cannot drift apart: a field added to one without
    the other renders an ordinary sheet and the payload goes nowhere,
    which ``test_every_field_reaches_the_sheet`` catches.
    """

    def at(name: str, ordinary):
        return payload if field == name else ordinary

    # Every component named, so ``schedule`` and ``insulation`` reach a
    # drawing at all: the default scheme spells four of the six.
    fs = Flowsheet(
        at("flowsheet name", "PLANT"),
        line_numbering_scheme="{size}-{schedule}-{service}-{sequence}-{spec}-{insulation}",
    )
    feed = fs.add(
        U.Feed(
            at("unit name", "F-1"),
            reference=at("off-page reference", "PFD-1"),
        )
    )
    pump = fs.add(U.Pump("P-101", description=at("unit description", "Feed pump")))
    product = fs.add(U.Product("Q-1"))
    fs.connect(feed.outlet, pump.suction, name=at("stream name", "S-1"))
    # Auto-named, because a stream the author named is drawn with that
    # name and its line number never reaches the sheet. The named one is
    # the run above; this is the one carrying the components.
    line = fs.connect(
        pump.discharge,
        product.inlet,
        size=at("line-number size", '6"'),
        schedule=at("line-number schedule", "40"),
        service=at("line-number service", "P"),
        sequence=at("line-number sequence", "1001"),
        spec=at("line-number spec", "A1A"),
        insulation=at("line-number insulation", "H"),
    )
    line.properties[at("stream property name", "Duty")] = at("stream property value", "12 kW")
    loop = fs.add_loop("F", at("loop number", "301"))
    fs.add_instrument("FT", loop, near=pump, at="N", offset=40)
    # Numbered rather than looped: a loop checks that an instrument's
    # letters open with its measured variable, so a payload cannot be
    # the letters on a balloon that belongs to one.
    fs.add_instrument(at("instrument letters", "PI"), 205, near=product, at="N", offset=40)

    fs.title_block = TitleBlock(
        # Blank by default, so the sheet's ``<title>`` falls back to the
        # flowsheet's name and that field is drawn too.
        title=at("title", ""),
        subtitle=at("subtitle", "Process Flow Diagram"),
        drawing_number=at("drawing number", "PFD-0001"),
        project=at("project", "A300"),
        client=at("client", "Acme"),
        company=at("company", "Contractor"),
        status=at("status", "ISSUED FOR REVIEW"),
        sheet=at("sheet", "1"),
        of_sheets=at("of sheets", "1"),
        scale=at("scale", "NTS"),
        drawn_by=at("drawn by", "AA"),
        checked_by=at("checked by", "BB"),
        approved_by=at("approved by", "CC"),
        date=at("date", "2026-01-01"),
        revisions=[Revision(rev=at("revision", "A"), date="2026-01-01", description="Issued")],
    )
    fs.annotations.append(equipment_list(fs, align="top-left"))
    fs.annotations.append(notes([at("note text", "Vent to flare.")]))
    fs.annotations.append(legend([("SS", at("legend entry", "316L"))]))
    fs.annotations.append(Annotation(title=at("annotation title", "REMARKS"), rows=["none"]))
    fs.annotations.append(
        TableBox(
            title=at("table title", "STREAMS"),
            headers=[at("table header", "Tag")],
            rows=[[at("table cell", "S-1")]],
            align="bottom-left",
        )
    )
    return fs


def _parsed(document: str) -> ET.Element:
    """*document*, parsed, or a failure saying it did not parse."""
    try:
        return ET.fromstring(document)
    except ET.ParseError as exc:
        pytest.fail(f"not well-formed XML: {exc}", pytrace=False)


def _carries_no_injected_markup(root: ET.Element) -> None:
    """No element or attribute the document did not mean to write."""
    for element in root.iter():
        for name in element.attrib:
            assert INJECTED not in name, f"{element.tag} carries an injected {name!r}"
        assert not element.tag.endswith("script"), "a payload became a <script> element"


def _every_reference_resolves(root: ET.Element) -> None:
    """Every ``url(#id)`` and ``href="#id"`` names an id in the document.

    Both halves of every pair the SVG mints: the arrowhead markers, and
    the ``<symbol>`` definitions each unit's ``<use>`` points at.
    """
    ids = {element.get("id") for element in root.iter() if element.get("id") is not None}
    for element in root.iter():
        for value in element.attrib.values():
            for ref in _URL.findall(value):
                assert ref in ids, f"url(#{ref}) names no id in the document"
        href = element.get("href") or element.get(_XLINK_HREF) or ""
        if href.startswith("#"):
            assert href[1:] in ids, f"href={href!r} names no id in the document"


@pytest.mark.parametrize("field", FIELDS)
@pytest.mark.parametrize("payload", PAYLOADS.values(), ids=list(PAYLOADS))
def test_a_hostile_value_cannot_break_the_sheet(field, payload):
    svg = _plant(payload, field).to_svg(**RENDERED)
    root = _parsed(svg)
    _carries_no_injected_markup(root)
    _every_reference_resolves(root)


@pytest.mark.parametrize("field", FIELDS)
@pytest.mark.parametrize("payload", PAYLOADS.values(), ids=list(PAYLOADS))
def test_a_hostile_value_cannot_break_the_drawio_export(field, payload):
    export = _plant(payload, field).to_drawio(**RENDERED)
    _carries_no_injected_markup(_parsed(export))


def _carries_no_html_beyond_br(root: ET.Element) -> None:
    """No cell ``value`` decodes, from XML, to a literal tag other than
    the library's own ``<br>``.

    draw.io reads a cell's ``value`` as *HTML*, a second parse the XML
    layer above knows nothing about. :func:`_carries_no_injected_markup`
    holds the XML layer to account -- no attribute or element name a
    payload invented -- and says nothing about this one: a payload
    surviving XML-decoding as ``<script>...</script>`` is perfectly
    well-formed XML and *is* the bug (issue #299), so it needs a check
    of its own.
    """
    for element in root.iter():
        value = element.get("value")
        if not value:
            continue
        bare = value.replace("<br>", "")
        assert "<" not in bare and ">" not in bare, (
            f"{element.tag} value={value!r} decodes to HTML markup draw.io "
            f"reads as a tag, not as the text it was given"
        )


@pytest.mark.parametrize("field", FIELDS)
@pytest.mark.parametrize("payload", PAYLOADS.values(), ids=list(PAYLOADS))
def test_a_hostile_value_cannot_become_html_in_the_drawio_export(field, payload):
    """draw.io interprets a cell's ``value`` as HTML, so a tag an author's
    field carries -- ``<script>alert(1)</script>`` as a unit's own
    description, say -- must survive as the literal characters, not
    render as markup. Well-formed XML is not enough to say that; see
    :func:`_carries_no_html_beyond_br`."""
    # Spelled out rather than `**RENDERED`: the dict's mixed str/bool
    # values type as a plain `dict[str, str | bool]`, which a checker
    # cannot match back against `to_drawio`'s per-parameter types once
    # unpacked, on this call site or the ones above it (pre-existing).
    export = _plant(payload, field).to_drawio(
        border="zone",
        diagram="p&id",
        connections="flanged",
        show_stream_table=True,
        check=False,
    )
    _carries_no_html_beyond_br(_parsed(export))


@pytest.mark.parametrize("field", FIELDS)
def test_every_field_reaches_the_sheet(field):
    """Each name in :data:`FIELDS` really does put a value on a drawing.

    Without this the property tests above pass by drawing nothing: a
    field renamed in one place and not the other stops carrying the
    payload, and a suite that never notices is a suite that has stopped
    testing that field.
    """
    marker = "ZQX"
    assert marker in _plant(marker, field).to_svg(**RENDERED), (
        f"{field!r} put nothing on the sheet: the name in FIELDS and the name "
        f"in _plant have drifted apart"
    )


def test_no_file_path_reaches_the_sheet(tmp_path):
    """Rendering to a file does not write the file's name into it.

    There is no path field to escape, and this is what says so. A sheet
    that echoed its own output path would carry whatever a caller had
    put in a directory name.
    """
    out = tmp_path / f"{INJECTED}.svg"
    _plant("ordinary", "flowsheet name").render(str(out))
    assert INJECTED not in out.read_text(encoding="utf-8")


# --- colour and dash: refused, not escaped ----------------------------


#: The payloads a colour is refused for. All of them but one: a long
#: run of letters is a *keyword*, and its shape is a colour's -- what
#: makes it useless is that it names no colour anybody has heard of,
#: which is a spelling question :func:`~pandid.streams.check_color`
#: leaves alone and says so.
HOSTILE_PAINTS = {name: value for name, value in PAYLOADS.items() if name != "very long"}


@pytest.mark.parametrize("payload", HOSTILE_PAINTS.values(), ids=list(HOSTILE_PAINTS))
@pytest.mark.parametrize("field", ["color", "dasharray"])
def test_a_paint_that_is_not_a_paint_is_refused(field, payload):
    """And the refusal names the field and quotes the value.

    Escaping these would leave a well-formed document that draws the
    wrong picture: an unrecognised ``stroke`` is ignored and the line
    disappears, an unrecognised ``stroke-dasharray`` is ignored and a
    signal line comes out solid. Neither reaches the author.
    """
    fs = _plant("ordinary", "flowsheet name")
    with pytest.raises(ValueError) as raised:
        setattr(fs.streams[0], field, payload)
    assert field in str(raised.value)
    assert repr(payload) in str(raised.value)


@pytest.mark.parametrize(
    "color",
    [
        "black",
        "#0a7",
        "#00aa77",
        "#0a7f",
        "#00aa77ff",
        "rgb(0, 170, 119)",
        "rgba(0,170,119,0.5)",
        "hsl(163 100% 33%)",
        "none",
        "currentColor",
        "transparent",
        "rebeccapurple",
    ],
)
def test_a_colour_that_is_a_colour_is_accepted(color):
    check_color(color)


@pytest.mark.parametrize("dash", ["7,4", "9,3,2,3", "9 3 2 3", "5", "0.5,1.25", "none"])
def test_a_dash_that_is_a_dash_is_accepted(dash):
    check_dasharray(dash)


def test_a_stream_keeps_the_paint_it_was_given():
    """The check refuses; it does not rewrite."""
    fs = _plant("ordinary", "flowsheet name")
    fs.streams[0].color = "#0a7"
    fs.streams[0].dasharray = "6,3"
    assert (fs.streams[0].color, fs.streams[0].dasharray) == ("#0a7", "6,3")
    svg = fs.to_svg(**RENDERED)
    assert 'stroke="#0a7"' in svg
    assert 'stroke-dasharray="6,3"' in svg


# --- ids ---------------------------------------------------------------


def test_a_marker_id_is_a_name_however_the_colour_is_spelled():
    """A colour function used to mint ``arrow_rgb(0,_170,_119)``.

    Which is a well-formed attribute value and not an XML name, so the
    definition was dropped and the arrowheads went missing in a browser
    while surviving a PDF export.
    """
    fs = _plant("ordinary", "flowsheet name")
    fs.streams[0].color = "rgb(0, 170, 119)"
    root = _parsed(fs.to_svg(check=False))
    _every_reference_resolves(root)
    marker = arrow_marker_id("rgb(0, 170, 119)")
    assert re.fullmatch(r"[A-Za-z_][A-Za-z0-9_.-]*", marker), marker
    assert f'id="{marker}"' in fs.to_svg(check=False)


def test_two_colours_never_share_one_marker():
    """The sanitising is lossy, so a digest carries what it drops.

    ``rgb(1,2,3)`` and ``rgb(1, 2, 3)`` differ only where the collapse
    is blind. Two arrowheads, two definitions.
    """
    assert arrow_marker_id("rgb(1,2,3)") != arrow_marker_id("rgb(1, 2, 3)")


def test_an_ordinary_colour_keeps_the_id_it_always_had():
    """The escaping is a no-op on a sheet that was already fine.

    ``tests/golden`` says the same thing over whole documents; this says
    it about the one id a change here would move first.
    """
    assert arrow_marker_id("black") == "arrow_black"
    assert arrow_marker_id("#0a7") == "arrow_0a7"


def test_ident_leaves_a_name_alone():
    assert ident("sym", "valve_control_s62.5x40") == "sym_valve_control_s62.5x40"


def test_ident_is_a_function_of_its_input_alone():
    """Called twice, it answers twice the same, or a reference would
    stop naming the definition it was minted beside."""
    assert ident("arrow", "rgb(1, 2, 3)") == ident("arrow", "rgb(1, 2, 3)")


def test_the_two_spellings_of_a_name_character_agree():
    """:data:`_UNSAFE_RUN` is :data:`_NAME_CHARS` negated, written out.

    Two spellings of one set is a bug waiting for whoever edits one.
    """
    for code in range(0x80):
        char = chr(code)
        assert (char in _NAME_CHARS) is not bool(_UNSAFE_RUN.fullmatch(char)), repr(char)


# --- the escaper itself -------------------------------------------------


@pytest.mark.parametrize("value", ["P-101", "FT-301", "6 in", "Cl2", "中文"])
def test_escaping_ordinary_content_changes_nothing(value):
    assert escaped(value) == value


def test_escaping_writes_the_five_and_drops_the_unwritable():
    assert escaped('A&B<C>"D"') == "A&amp;B&lt;C&gt;&quot;D&quot;"
    assert escaped("a\x00b\x08c") == "abc"
    assert writable("a\tb\nc\rd") == "a\tb\nc\rd"


def test_an_inch_mark_is_escaped_and_stays_escaped():
    """A line number carries one, so the goldens carry ``&quot;``.

    Not an over-escape to be tidied away: a bare ``"`` inside an
    attribute value ends it, and ``6"-P-1001-A1A`` is written into
    plenty of them.
    """
    assert escaped('6"-P-1001-A1A') == "6&quot;-P-1001-A1A"
