#!/usr/bin/env python3
"""Generate pfd/render/_vendored_symbols.py from the Equinor engineering-symbols
manifest (MIT). See NOTICE for attribution.

Each mapped symbol becomes a `registry.register(kind, Symbol(...), variant)` call.
Port anchors are placed on the symbol's bounding-box edge at each Equinor
connector's cross-coordinate, keyed by the connector's outward direction:

    Equinor direction  0 -> N (top),  90 -> E (right),
                     180 -> S (bottom), 270 -> W (left)

Geometry comes from each entry's `geometryString` (a single merged fill path),
which avoids the id collisions of embedding whole <svg> documents.

Run:  python scripts/vendor_symbols.py
"""
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
MANIFEST = HERE / "vendor_data" / "equinor-engineering-symbols.json"
OUT = HERE.parent / "pfd" / "render" / "_vendored_symbols.py"

# (kind, variant) -> (equinor_code, {port_name: (edge, along)})
# `edge` in N/S/E/W; `along` is the coordinate along that edge (symbol units),
# chosen to line up with the drawn nozzle. Only clean fits are vendored;
# multi-port units (hex/column/reactor/separator) and the boundary/utility
# symbols stay hand-drawn in symbols.py.
KIND_MAP = {
    # Valves — the headline family, all inline (inlet W / outlet E).
    ("valve", "default"):   ("PV005A", {"inlet": ("W", 12), "outlet": ("E", 12)}),   # gate
    ("valve", "gate"):      ("PV005A", {"inlet": ("W", 12), "outlet": ("E", 12)}),
    ("valve", "globe"):     ("PV007B", {"inlet": ("W", 12), "outlet": ("E", 12)}),
    ("valve", "ball"):      ("PV018A", {"inlet": ("W", 12), "outlet": ("E", 12)}),
    ("valve", "control"):   ("PV016A", {"inlet": ("W", 21.5), "outlet": ("E", 21.5)}),
    ("valve", "check"):     ("PV022A", {"inlet": ("W", 24), "outlet": ("E", 24)}),
    ("valve", "butterfly"): ("PV023A", {"inlet": ("W", 29), "outlet": ("E", 29)}),
    ("valve", "relief"):    ("ND0020", {"inlet": ("W", 47.5), "outlet": ("E", 47.5)}),
    # Rotating equipment (suction left, discharge top/side).
    ("pump", "default"):        ("PP001A", {"suction": ("W", 40.5), "discharge": ("N", 48)}),
    ("compressor", "default"):  ("PP003A", {"suction": ("W", 40.5), "discharge": ("N", 48)}),
    ("blower", "default"):      ("PP007A", {"suction": ("W", 40.5), "discharge": ("E", 13)}),
    # Vessels / tanks.
    ("vessel", "default"):  ("PT002A", {"inlet": ("W", 108), "outlet": ("E", 108)}),
    ("tank", "default"):    ("PT005A", {"inlet": ("N", 30), "outlet": ("S", 48)}),
    ("tank", "dished"):     ("PT006A", {"inlet": ("N", 30), "outlet": ("S", 48)}),
    # Fittings. (Instrument bubbles come with the instrumentation batch, which
    # also adds tag text + signal line types.)
    ("reducer", "default"):    ("STPL008", {"inlet": ("W", 12), "outlet": ("E", 12)}),
    ("nozzle", "default"):     ("PA007A", {"inlet": ("N", 12)}),
}


def edge_port(edge, along, w, h):
    """Place a port on the given bounding-box edge at `along` (symbol units)."""
    if edge == "N":
        return (float(along), 0.0)
    if edge == "S":
        return (float(along), float(h))
    if edge == "E":
        return (float(w), float(along))
    return (0.0, float(along))  # W


def build():
    data = json.loads(MANIFEST.read_text())
    lines = [
        '"""Equinor-derived equipment symbols (MIT). GENERATED by',
        'scripts/vendor_symbols.py — do not edit by hand. See NOTICE for attribution."""',
        "",
        "",
        "def register_vendored(registry):",
        "    \"\"\"Register the vendored Equinor symbols, overriding any hand-drawn",
        "    defaults of the same (kind, variant).\"\"\"",
        "    from pfd.render.symbols import Symbol",
        "",
    ]
    for (kind, variant), (code, port_map) in KIND_MAP.items():
        e = data[code]
        w, h = e["width"], e["height"]
        ports = {pname: edge_port(edge, along, w, h)
                 for pname, (edge, along) in port_map.items()}
        sid = kind if variant == "default" else f"{kind}_{variant}"
        geom = e["geometryString"]
        svg = f'<g id="sym_{sid}"><path d="{geom}" fill="#111111"/></g>'
        lines += [
            f"    # Equinor {code} -> {kind}/{variant}",
            f"    registry.register({kind!r}, Symbol(",
            f"        svg={svg!r},",
            f"        width={w}, height={h},",
            f"        ports={ports!r},",
            f"    ), {variant!r})",
            "",
        ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({len(KIND_MAP)} symbols)")


if __name__ == "__main__":
    build()
