"""Equipment classes: named classes for what a piece of plant is.

GENERATED by scripts/gen_devices.py. Do not edit by hand.

:mod:`pandid.units` models equipment as a ``kind`` and a ``variant``, as
the symbol registry is keyed. This module adds one class per device, so

    * an engineer looking for a cyclone finds :class:`Cyclone` rather
      than ``Separator(variant="cyclone")``;
    * a type checker sees ``cyclone.underflow``, because the ports are
      declared on the class;
    * an equipment list reads as equipment.

A class is what the equipment is and ``variant=`` is how it is drawn:
a variant becomes a class when it names a distinct scheduled item, and
stays a variant for a support, roof, cladding, attitude, drawn internal,
certification rating or body style. A gate valve and a ball valve are
one class; a check valve, which has no actuator, is its own.

The base-class form, such as ``Separator(variant="cyclone")``, stays
supported and is the only way to reach drawings without a class;
``pandid.render.symbols.default_registry`` is the whole catalogue.

:class:`Cyclone`, :class:`GravitySeparator` and
:class:`ElectrostaticPrecipitator` collect dust, so their draws are
``overflow`` (gas) and ``underflow`` (catch), as in classification and
solid-liquid separation. ``Separator`` draws the same pair for those
variants; the artwork's ``vapor``/``liquid`` anchors are mapped in
:attr:`pandid.units.Separator._VARIANT_ANCHORS`.

This module imports its bases from :mod:`pandid.units`, so it is not
star-imported there. Use ``from pandid import devices`` or the package,
which re-exports every class.
"""

from typing import TYPE_CHECKING, Any, Literal, overload

from pandid.ports import Port
from pandid.units import (
    Compressor,
    Conveyor,
    Crusher,
    Dryer,
    Evaporator,
    Feeder,
    Filter,
    Fitting,
    HeatExchanger,
    Kiln,
    Mill,
    Pump,
    Reactor,
    ScreeningDevice,
    Separator,
    Tank,
    Valve,
)

__all__ = [
    "CentrifugalPump",
    "GearPump",
    "ScrewPump",
    "PeristalticPump",
    "SubmersiblePump",
    "VacuumPump",
    "CentrifugalCompressor",
    "ReciprocatingCompressor",
    "RotaryCompressor",
    "LiquidRingCompressor",
    "ShellAndTubeExchanger",
    "DoublePipeExchanger",
    "KettleReboiler",
    "Condenser",
    "AirCooledExchanger",
    "PlateExchanger",
    "SpiralExchanger",
    "ThinFilmEvaporator",
    "CalandriaEvaporator",
    "FallingFilmEvaporator",
    "ClimbingFilmEvaporator",
    "PlateEvaporator",
    "RotaryKiln",
    "FluidizedBedCalciner",
    "ShaftKiln",
    "Cyclone",
    "GravitySeparator",
    "ElectrostaticPrecipitator",
    "Screen",
    "ImpactSeparator",
    "MagneticSeparator",
    "Scrubber",
    "VenturiScrubber",
    "KnockoutDrum",
    "DustCollector",
    "RotaryDrumFilter",
    "FilterPress",
    "IonExchanger",
    "RotaryDryer",
    "FluidizedBedDryer",
    "SprayDryer",
    "ShelfDryer",
    "TurboDryer",
    "BeltDryer",
    "JawCrusher",
    "ConeCrusher",
    "HammerCrusher",
    "ImpactCrusher",
    "RollerCrusher",
    "HammerMill",
    "ImpactMill",
    "RollerMill",
    "VibratingMill",
    "ScrewConveyor",
    "RotaryValveFeeder",
    "RotaryTableFeeder",
    "MeteringFeeder",
    "CoarseRakeScreen",
    "FineRakeScreen",
    "CoarseAndFineScreen",
    "VibratingScreen",
    "RotaryDrumScreen",
    "ReelScreen",
    "ThreeWayValve",
    "ControlValve",
    "SolenoidValve",
    "ReliefValve",
    "PressureRegulator",
    "MotorOperatedValve",
    "CheckValve",
    "SpectacleBlind",
    "SteamTrap",
    "FlowElement",
    "StirredTankReactor",
    "GasHolder",
]


class CentrifugalPump(Pump):
    """Centrifugal pump: the volute-and-impeller workhorse.

    What ``Pump`` draws when it is asked for by name, under the name a
    schedule calls it. Head falls as flow rises, so it throttles on a
    control valve rather than on a relief; contrast :class:`GearPump`
    and :class:`ScrewPump`, which are positive displacement and do not.

    Parameters are those of :class:`~pandid.units.Pump`.
    """

    kind = "pump"
    VARIANTS = ("default",)
    PORTS = [("suction", "inlet", "process"), ("discharge", "outlet", "process")]

    suction: Port
    discharge: Port


class GearPump(Pump):
    """Gear pump: positive displacement, for viscous or metered duty.

    Two meshing gears carry fluid round the casing, so flow is set by
    speed and is very nearly independent of discharge pressure. That is
    why a positive displacement pump is protected by a relief valve and
    a centrifugal is not: a closed discharge has nowhere to go.

    Parameters are those of :class:`~pandid.units.Pump`.
    """

    kind = "pump"
    VARIANTS = ("default", "gear")
    VARIANT_ALIASES = {"default": "gear"}
    PORTS = [("suction", "inlet", "process"), ("discharge", "outlet", "process")]

    suction: Port
    discharge: Port


class ScrewPump(Pump):
    """Screw pump: positive displacement, for viscous duty.

    One or more screws in a close-fitting barrel, moving a smooth,
    pulsation-free flow along the axis. The same relief-valve rule as
    :class:`GearPump`.

    Parameters are those of :class:`~pandid.units.Pump`.
    """

    kind = "pump"
    VARIANTS = ("default", "screw")
    VARIANT_ALIASES = {"default": "screw"}
    PORTS = [("suction", "inlet", "process"), ("discharge", "outlet", "process")]

    suction: Port
    discharge: Port


class PeristalticPump(Pump):
    """Peristaltic pump: rollers squeeze a tube, wetting nothing.

    The metering pump for a slurry or a reagent that must not meet a
    seal or an impeller: the fluid touches the hose and nothing else.
    Both connections leave the top of the head, which is where the
    stencil draws the tube.

    Parameters are those of :class:`~pandid.units.Pump`.
    """

    kind = "pump"
    VARIANTS = ("default", "peristaltic")
    VARIANT_ALIASES = {"default": "peristaltic"}
    PORTS = [("suction", "inlet", "process"), ("discharge", "outlet", "process")]

    suction: Port
    discharge: Port


class SubmersiblePump(Pump):
    """Submersible (sump) pump: it stands in the liquid it pumps.

    The suction is the strainer plate it sits on rather than a piped
    nozzle, so the drawing is piped from underneath; the discharge is
    the riser out of the casing.

    Parameters are those of :class:`~pandid.units.Pump`.
    """

    kind = "pump"
    VARIANTS = ("default", "submersible")
    VARIANT_ALIASES = {"default": "submersible"}
    PORTS = [("suction", "inlet", "process"), ("discharge", "outlet", "process")]

    suction: Port
    discharge: Port


class VacuumPump(Pump):
    """Vacuum pump: the machine that pulls a system below atmospheric.

    Drawn as a pump rather than as a compressor because that is the
    stencil the set files it under; a liquid-ring machine doing the same
    duty is :class:`LiquidRingCompressor`.

    Parameters are those of :class:`~pandid.units.Pump`.
    """

    kind = "pump"
    VARIANTS = ("default", "vacuum")
    VARIANT_ALIASES = {"default": "vacuum"}
    PORTS = [("suction", "inlet", "process"), ("discharge", "outlet", "process")]

    suction: Port
    discharge: Port


class CentrifugalCompressor(Compressor):
    """Centrifugal compressor: dynamic compression, for large gas flows.

    What ``Compressor`` draws when it is asked for by name. Its stable
    range is bounded by surge at low flow, which is what the anti-surge
    recycle round one is for; a reciprocating machine has no such limit
    and needs no such line.

    Parameters are those of :class:`~pandid.units.Compressor`.
    """

    kind = "compressor"
    VARIANTS = ("default",)
    PORTS = [("suction", "inlet", "process"), ("discharge", "outlet", "process")]

    suction: Port
    discharge: Port


class ReciprocatingCompressor(Compressor):
    """Reciprocating compressor: for high ratio or low flow.

    A piston in a cylinder, so the discharge pulses and the ratio is set
    by geometry rather than by speed. Like every positive displacement
    machine it is protected by a relief valve on the discharge.

    Parameters are those of :class:`~pandid.units.Compressor`.
    """

    kind = "compressor"
    VARIANTS = ("default", "reciprocating")
    VARIANT_ALIASES = {"default": "reciprocating"}
    PORTS = [("suction", "inlet", "process"), ("discharge", "outlet", "process")]

    suction: Port
    discharge: Port


class RotaryCompressor(Compressor):
    """Rotary compressor: screws or lobes, and oil-free duty.

    The plant-air and blower-service machine: steady flow, modest ratio,
    and no valves to pulse.

    Parameters are those of :class:`~pandid.units.Compressor`.
    """

    kind = "compressor"
    VARIANTS = ("default", "rotary")
    VARIANT_ALIASES = {"default": "rotary"}
    PORTS = [("suction", "inlet", "process"), ("discharge", "outlet", "process")]

    suction: Port
    discharge: Port


class LiquidRingCompressor(Compressor):
    """Liquid-ring compressor: a rotating liquid seal does the work.

    Wet, tolerant of carryover and inherently cool, which is why it is
    the machine on a vacuum system handling condensable or dirty vapour.
    It carries a service liquid, which the sheet draws as an ordinary
    connection to the machine rather than as a nozzle of its own.

    Parameters are those of :class:`~pandid.units.Compressor`.
    """

    kind = "compressor"
    VARIANTS = ("default", "liquid_ring")
    VARIANT_ALIASES = {"default": "liquid_ring"}
    PORTS = [("suction", "inlet", "process"), ("discharge", "outlet", "process")]

    suction: Port
    discharge: Port


class ShellAndTubeExchanger(HeatExchanger):
    """Shell-and-tube exchanger: a tube bundle inside a shell.

    The default exchanger and the one most of the family's drawings are
    styles of: the ISO circle-and-zigzag (``default``, ``shell_tube``),
    the U-tube and hairpin bundles that turn round inside the shell
    (``u_tube``, ``hairpin``), the horizontal elevation a real sheet
    draws (``straight_tubes``) and the finned bundle in the same casing
    (``finned``).

    Nozzles are named for the **side of the equipment** they sit on,
    never for the duty the stream carries: which fluid runs in the shell
    and which in the tubes is a design decision worth recording, and hot
    and cold invert between operating cases while the nozzle stays where
    it is.

    Parameters are those of :class:`~pandid.units.HeatExchanger`.
    """

    kind = "hex"
    VARIANTS = ("default", "shell_tube", "u_tube", "straight_tubes", "finned", "hairpin")
    PORTS = [
        ("shell_in", "inlet", "process"),
        ("shell_out", "outlet", "process"),
        ("tube_in", "inlet", "process"),
        ("tube_out", "outlet", "process"),
    ]

    shell_in: Port
    shell_out: Port
    tube_in: Port
    tube_out: Port


class DoublePipeExchanger(HeatExchanger):
    """Double-pipe exchanger: a pipe in a pipe, drawn as a hairpin.

    The small-duty exchanger, and the one whose two sides really are a
    tube and an annulus. Both fluids enter at the same end and turn
    round at the far one, so neither side has an east nozzle.

    Parameters are those of :class:`~pandid.units.HeatExchanger`.
    """

    kind = "hex"
    VARIANTS = ("default", "double_pipe")
    VARIANT_ALIASES = {"default": "double_pipe"}
    PORTS = [
        ("shell_in", "inlet", "process"),
        ("shell_out", "outlet", "process"),
        ("tube_in", "inlet", "process"),
        ("tube_out", "outlet", "process"),
    ]

    shell_in: Port
    shell_out: Port
    tube_in: Port
    tube_out: Port


class KettleReboiler(HeatExchanger):
    """Kettle reboiler: a bundle in an enlarged shell, with a weir.

    The one exchanger with a nozzle more. ``bottoms`` is the draw at the
    weir end: what does not boil overflows the plate and leaves the
    bottom of the shell, which is where a tower's bottoms product
    physically gets off the sheet. The draw belongs on the exchanger,
    not on an invented splitter in the sump line.

    The heating medium is the **tube** side; the process boils in the
    shell. The stencil draws one channel-head opening, so ``tube_out``
    takes the shell's far dished head.

    Parameters are those of :class:`~pandid.units.HeatExchanger`.
    """

    kind = "hex"
    VARIANTS = ("default", "kettle")
    VARIANT_ALIASES = {"default": "kettle"}
    PORTS = [
        ("shell_in", "inlet", "process"),
        ("shell_out", "outlet", "process"),
        ("tube_in", "inlet", "process"),
        ("tube_out", "outlet", "process"),
        ("bottoms", "outlet", "liquid"),
    ]

    shell_in: Port
    shell_out: Port
    tube_in: Port
    tube_out: Port
    bottoms: Port


class Condenser(HeatExchanger):
    """Condenser: the exchanger taking an overhead vapour to liquid.

    The circle-and-zigzag with the heat-removed arrow across it, so the
    sides read the same way as the rest of the shell-and-tube family.
    For the single-stream utility symbol, where the cooling medium is a
    connection rather than a side, reach for
    :class:`pandid.units.Cooler` instead.

    Parameters are those of :class:`~pandid.units.HeatExchanger`.
    """

    kind = "hex"
    VARIANTS = ("default", "condenser")
    VARIANT_ALIASES = {"default": "condenser"}
    PORTS = [
        ("shell_in", "inlet", "process"),
        ("shell_out", "outlet", "process"),
        ("tube_in", "inlet", "process"),
        ("tube_out", "outlet", "process"),
    ]

    shell_in: Port
    shell_out: Port
    tube_in: Port
    tube_out: Port


class AirCooledExchanger(HeatExchanger):
    """Air-cooled exchanger: a finned bundle with air blown over it.

    The only piped side is the tube bundle. There is no shell, so the
    nozzles say so: ``air_in`` and ``air_out`` are the induced-draft
    bay's own faces, under the bundle and out through the fan, and
    neither is a pipe. That is why this is a class and not a style -- an
    exchanger with no shell cannot carry ``shell_in``.

    Parameters are those of :class:`~pandid.units.HeatExchanger`.
    """

    kind = "hex"
    VARIANTS = ("default", "air_cooled")
    VARIANT_ALIASES = {"default": "air_cooled"}
    PORTS = [
        ("tube_in", "inlet", "process"),
        ("tube_out", "outlet", "process"),
        ("air_in", "inlet", "process"),
        ("air_out", "outlet", "process"),
    ]

    tube_in: Port
    tube_out: Port
    air_in: Port
    air_out: Port


class PlateExchanger(HeatExchanger):
    """Plate exchanger: a pack of plates, two circuits through it.

    Neither circuit is a shell or a tube and the two are physically
    interchangeable, so they are **lettered** rather than named:
    ``side_a`` and ``side_b``, each following the diagonal the artwork
    actually draws.

    Parameters are those of :class:`~pandid.units.HeatExchanger`.
    """

    kind = "hex"
    VARIANTS = ("default", "plate")
    VARIANT_ALIASES = {"default": "plate"}
    PORTS = [
        ("side_a_in", "inlet", "process"),
        ("side_a_out", "outlet", "process"),
        ("side_b_in", "inlet", "process"),
        ("side_b_out", "outlet", "process"),
    ]

    side_a_in: Port
    side_a_out: Port
    side_b_in: Port
    side_b_out: Port


class SpiralExchanger(HeatExchanger):
    """Spiral exchanger: two channels coiled about a common centre.

    Lettered sides for :class:`PlateExchanger`'s reason: neither channel
    is a shell or a tube. The self-cleaning geometry is what puts one in
    fouling or slurry duty.

    Parameters are those of :class:`~pandid.units.HeatExchanger`.
    """

    kind = "hex"
    VARIANTS = ("default", "spiral")
    VARIANT_ALIASES = {"default": "spiral"}
    PORTS = [
        ("side_a_in", "inlet", "process"),
        ("side_a_out", "outlet", "process"),
        ("side_b_in", "inlet", "process"),
        ("side_b_out", "outlet", "process"),
    ]

    side_a_in: Port
    side_a_out: Port
    side_b_in: Port
    side_b_out: Port


class ThinFilmEvaporator(HeatExchanger):
    """Thin-film evaporator: a rotor spreads feed on a heated wall.

    The one evaporator in the set, and the one exchanger whose two sides
    are a **jacket** and a **product** side. Product runs top to bottom
    -- onto the wiper at the top, concentrate out of the cone apex --
    and the heating medium goes through the jacket, which is why neither
    pair borrows the shell-and-tube names.

    Parameters are those of :class:`~pandid.units.HeatExchanger`.
    """

    kind = "hex"
    VARIANTS = ("default", "thin_film")
    VARIANT_ALIASES = {"default": "thin_film"}
    PORTS = [
        ("jacket_in", "inlet", "process"),
        ("jacket_out", "outlet", "process"),
        ("product_in", "inlet", "process"),
        ("product_out", "outlet", "process"),
    ]

    jacket_in: Port
    jacket_out: Port
    product_in: Port
    product_out: Port


class CalandriaEvaporator(Evaporator):
    """Calandria (short-tube) evaporator: a short bundle with a central downcomer.

    The sugar and salt workhorse, and the body most people picture when
    they hear "evaporator": liquor rises through a short heated bundle
    and falls back down the middle, so the machine circulates on its own
    heat with nothing turning in it.

    Parameters are those of :class:`~pandid.units.Evaporator`.
    """

    kind = "evaporator"
    VARIANTS = ("default", "calandria")
    VARIANT_ALIASES = {"default": "calandria"}
    PORTS = [
        ("feed", "inlet", "feed"),
        ("vapor", "outlet", "vapor"),
        ("concentrate", "outlet", "liquid"),
        ("heating_in", "inlet", "utility"),
        ("condensate", "outlet", "utility"),
    ]

    feed: Port
    vapor: Port
    concentrate: Port
    heating_in: Port
    condensate: Port


class FallingFilmEvaporator(Evaporator):
    """Falling-film evaporator: liquor fed onto a distributor over long tubes.

    The low-holdup, low-temperature-rise effect a multiple-effect train
    is built from, and what heat-sensitive duties -- dairy, juice,
    caustic liquor -- reach for. The distributor over the top tubesheet
    is drawn because it is the machine's defining internal: a tube it
    fails to wet dries out and fouls.

    Parameters are those of :class:`~pandid.units.Evaporator`.
    """

    kind = "evaporator"
    VARIANTS = ("default", "falling_film")
    VARIANT_ALIASES = {"default": "falling_film"}
    PORTS = [
        ("feed", "inlet", "feed"),
        ("vapor", "outlet", "vapor"),
        ("concentrate", "outlet", "liquid"),
        ("heating_in", "inlet", "utility"),
        ("condensate", "outlet", "utility"),
    ]

    feed: Port
    vapor: Port
    concentrate: Port
    heating_in: Port
    condensate: Port


class ClimbingFilmEvaporator(Evaporator):
    """Climbing-film evaporator: liquor fed into the foot of the tubes.

    The same long-tube body as :class:`FallingFilmEvaporator` with the
    feed at the other end: the liquor's own vapour carries it up the
    tube wall as a film. Simpler, since there is no distributor to keep
    even, and it needs a temperature difference to get the film started.

    Parameters are those of :class:`~pandid.units.Evaporator`.
    """

    kind = "evaporator"
    VARIANTS = ("default", "climbing_film")
    VARIANT_ALIASES = {"default": "climbing_film"}
    PORTS = [
        ("feed", "inlet", "feed"),
        ("vapor", "outlet", "vapor"),
        ("concentrate", "outlet", "liquid"),
        ("heating_in", "inlet", "utility"),
        ("condensate", "outlet", "utility"),
    ]

    feed: Port
    vapor: Port
    concentrate: Port
    heating_in: Port
    condensate: Port


class PlateEvaporator(Evaporator):
    """Plate evaporator: a gasketed or welded plate pack in place of a bundle.

    Compact, low holdup, and dismantled for cleaning, which is what puts
    it in food and pharmaceutical duty. No tubesheets: the plates are the
    heating surface and they are clamped in a frame of their own.

    Parameters are those of :class:`~pandid.units.Evaporator`.
    """

    kind = "evaporator"
    VARIANTS = ("default", "plate")
    VARIANT_ALIASES = {"default": "plate"}
    PORTS = [
        ("feed", "inlet", "feed"),
        ("vapor", "outlet", "vapor"),
        ("concentrate", "outlet", "liquid"),
        ("heating_in", "inlet", "utility"),
        ("condensate", "outlet", "utility"),
    ]

    feed: Port
    vapor: Port
    concentrate: Port
    heating_in: Port
    condensate: Port


class RotaryKiln(Kiln):
    """Rotary kiln: a sloping shell, turning, fired down its length.

    Cement, lime, alumina and every roasting duty there is, and what
    ``Kiln`` draws when it is asked for by name. The fall from feed end
    to discharge is what moves the charge, so the drawing may not be
    turned; the riding rings are what tell the shell from a pipe.

    Parameters are those of :class:`~pandid.units.Kiln`.
    """

    kind = "kiln"
    VARIANTS = ("default",)
    PORTS = [
        ("feed", "inlet", "feed"),
        ("product", "outlet", "process"),
        ("offgas", "outlet", "vapor"),
        ("fuel", "inlet", "feed"),
        ("air", "inlet", "utility"),
    ]

    feed: Port
    product: Port
    offgas: Port
    fuel: Port
    air: Port


class FluidizedBedCalciner(Kiln):
    """Fluidised-bed or gas-suspension calciner: solids held in the gas that fires them.

    What a refinery built this century calcines hydrate in, and what a
    roaster does its work in. Product is drawn over a weir out of the
    bed and the spent gas leaves the freeboard above it, which is the
    nozzle a :class:`FluidizedBedDryer` standing in for one did not
    have.

    Parameters are those of :class:`~pandid.units.Kiln`.
    """

    kind = "kiln"
    VARIANTS = ("default", "fluidized_bed")
    VARIANT_ALIASES = {"default": "fluidized_bed"}
    PORTS = [
        ("feed", "inlet", "feed"),
        ("product", "outlet", "process"),
        ("offgas", "outlet", "vapor"),
        ("fuel", "inlet", "feed"),
        ("air", "inlet", "utility"),
    ]

    feed: Port
    product: Port
    offgas: Port
    fuel: Port
    air: Port


class ShaftKiln(Kiln):
    """Vertical shaft kiln: a column of burden, fired at its middle.

    The lime kiln, and the counter-current machine every fuel argument
    about calcination starts from: the charge preheats against the gas
    leaving, calcines at the burners, and cools against the air entering
    under it.

    Parameters are those of :class:`~pandid.units.Kiln`.
    """

    kind = "kiln"
    VARIANTS = ("default", "shaft")
    VARIANT_ALIASES = {"default": "shaft"}
    PORTS = [
        ("feed", "inlet", "feed"),
        ("product", "outlet", "process"),
        ("offgas", "outlet", "vapor"),
        ("fuel", "inlet", "feed"),
        ("air", "inlet", "utility"),
    ]

    feed: Port
    product: Port
    offgas: Port
    fuel: Port
    air: Port


class Cyclone(Separator):
    """Cyclone separator: a vortex throws the heavy phase down.

    The gas-solid workhorse -- off a spray dryer, a fluidised bed, a
    mill -- and the hydrocyclone in a classifying duty. ISO 15519-1
    symbol X 2618, and one of the two the standard names as symbols
    gravity fixes the attitude of: the apex points down and the drawing
    says nothing true turned.

    The draws are ``overflow`` and ``underflow``, not ``vapor`` and
    ``liquid``, because the apex discharges a solid catch.
    ``Separator(variant="cyclone")`` draws the same pair.

    Parameters are those of :class:`~pandid.units.Separator`.
    """

    kind = "separator"
    VARIANTS = ("default", "cyclone")
    VARIANT_ALIASES = {"default": "cyclone"}
    PORTS = [("overflow", "outlet", "process"), ("underflow", "outlet", "process")]

    overflow: Port
    underflow: Port

    if TYPE_CHECKING:

        @overload
        def __new__(cls, name: str, n_feeds: Literal[1] = 1,
                    *args: Any, **kwargs: Any) -> "Cyclone1": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[2],
                    *args: Any, **kwargs: Any) -> "Cyclone2": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[3],
                    *args: Any, **kwargs: Any) -> "Cyclone3": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[4],
                    *args: Any, **kwargs: Any) -> "Cyclone4": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[5],
                    *args: Any, **kwargs: Any) -> "Cyclone5": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[6],
                    *args: Any, **kwargs: Any) -> "Cyclone6": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[7],
                    *args: Any, **kwargs: Any) -> "Cyclone7": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[8],
                    *args: Any, **kwargs: Any) -> "Cyclone8": ...

        @overload
        def __new__(cls, name: str, n_feeds: int,
                    *args: Any, **kwargs: Any) -> "Cyclone": ...
        def __new__(cls, name: str, n_feeds: int = 1,
                    *args: Any, **kwargs: Any) -> "Cyclone": ...


if TYPE_CHECKING:

    class Cyclone1(Cyclone):
        """Cyclone declaring ``feed_1`` for type checkers."""

        feed_1: Port

    class Cyclone2(Cyclone):
        """Cyclone declaring ``feed_1`` to ``feed_2`` for type checkers."""

        feed_1: Port
        feed_2: Port

    class Cyclone3(Cyclone):
        """Cyclone declaring ``feed_1`` to ``feed_3`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port

    class Cyclone4(Cyclone):
        """Cyclone declaring ``feed_1`` to ``feed_4`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port

    class Cyclone5(Cyclone):
        """Cyclone declaring ``feed_1`` to ``feed_5`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port

    class Cyclone6(Cyclone):
        """Cyclone declaring ``feed_1`` to ``feed_6`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port

    class Cyclone7(Cyclone):
        """Cyclone declaring ``feed_1`` to ``feed_7`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port
        feed_7: Port

    class Cyclone8(Cyclone):
        """Cyclone declaring ``feed_1`` to ``feed_8`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port
        feed_7: Port
        feed_8: Port


class GravitySeparator(Separator):
    """Gravity separator: velocity drops and the heavy phase falls.

    The crudest gas-solid separator there is, and usually the first
    stage ahead of a cyclone or a filter. ``overflow`` and ``underflow``
    for :class:`Cyclone`'s reason.

    Parameters are those of :class:`~pandid.units.Separator`.
    """

    kind = "separator"
    VARIANTS = ("default", "gravity")
    VARIANT_ALIASES = {"default": "gravity"}
    PORTS = [("overflow", "outlet", "process"), ("underflow", "outlet", "process")]

    overflow: Port
    underflow: Port

    if TYPE_CHECKING:

        @overload
        def __new__(cls, name: str, n_feeds: Literal[1] = 1,
                    *args: Any, **kwargs: Any) -> "GravitySeparator1": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[2],
                    *args: Any, **kwargs: Any) -> "GravitySeparator2": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[3],
                    *args: Any, **kwargs: Any) -> "GravitySeparator3": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[4],
                    *args: Any, **kwargs: Any) -> "GravitySeparator4": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[5],
                    *args: Any, **kwargs: Any) -> "GravitySeparator5": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[6],
                    *args: Any, **kwargs: Any) -> "GravitySeparator6": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[7],
                    *args: Any, **kwargs: Any) -> "GravitySeparator7": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[8],
                    *args: Any, **kwargs: Any) -> "GravitySeparator8": ...

        @overload
        def __new__(cls, name: str, n_feeds: int,
                    *args: Any, **kwargs: Any) -> "GravitySeparator": ...
        def __new__(cls, name: str, n_feeds: int = 1,
                    *args: Any, **kwargs: Any) -> "GravitySeparator": ...


if TYPE_CHECKING:

    class GravitySeparator1(GravitySeparator):
        """GravitySeparator declaring ``feed_1`` for type checkers."""

        feed_1: Port

    class GravitySeparator2(GravitySeparator):
        """GravitySeparator declaring ``feed_1`` to ``feed_2`` for type checkers."""

        feed_1: Port
        feed_2: Port

    class GravitySeparator3(GravitySeparator):
        """GravitySeparator declaring ``feed_1`` to ``feed_3`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port

    class GravitySeparator4(GravitySeparator):
        """GravitySeparator declaring ``feed_1`` to ``feed_4`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port

    class GravitySeparator5(GravitySeparator):
        """GravitySeparator declaring ``feed_1`` to ``feed_5`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port

    class GravitySeparator6(GravitySeparator):
        """GravitySeparator declaring ``feed_1`` to ``feed_6`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port

    class GravitySeparator7(GravitySeparator):
        """GravitySeparator declaring ``feed_1`` to ``feed_7`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port
        feed_7: Port

    class GravitySeparator8(GravitySeparator):
        """GravitySeparator declaring ``feed_1`` to ``feed_8`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port
        feed_7: Port
        feed_8: Port


class ElectrostaticPrecipitator(Separator):
    """Electrostatic precipitator: charged particles migrate to a plate.

    The high-efficiency dust collector on a flue-gas or a kiln duty,
    rapped clear into the hopper below. ``overflow`` and ``underflow``
    for :class:`Cyclone`'s reason.

    Parameters are those of :class:`~pandid.units.Separator`.
    """

    kind = "separator"
    VARIANTS = ("default", "electrostatic")
    VARIANT_ALIASES = {"default": "electrostatic"}
    PORTS = [("overflow", "outlet", "process"), ("underflow", "outlet", "process")]

    overflow: Port
    underflow: Port

    if TYPE_CHECKING:

        @overload
        def __new__(cls, name: str, n_feeds: Literal[1] = 1,
                    *args: Any, **kwargs: Any) -> "ElectrostaticPrecipitator1": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[2],
                    *args: Any, **kwargs: Any) -> "ElectrostaticPrecipitator2": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[3],
                    *args: Any, **kwargs: Any) -> "ElectrostaticPrecipitator3": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[4],
                    *args: Any, **kwargs: Any) -> "ElectrostaticPrecipitator4": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[5],
                    *args: Any, **kwargs: Any) -> "ElectrostaticPrecipitator5": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[6],
                    *args: Any, **kwargs: Any) -> "ElectrostaticPrecipitator6": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[7],
                    *args: Any, **kwargs: Any) -> "ElectrostaticPrecipitator7": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[8],
                    *args: Any, **kwargs: Any) -> "ElectrostaticPrecipitator8": ...

        @overload
        def __new__(cls, name: str, n_feeds: int,
                    *args: Any, **kwargs: Any) -> "ElectrostaticPrecipitator": ...
        def __new__(cls, name: str, n_feeds: int = 1,
                    *args: Any, **kwargs: Any) -> "ElectrostaticPrecipitator": ...


if TYPE_CHECKING:

    class ElectrostaticPrecipitator1(ElectrostaticPrecipitator):
        """ElectrostaticPrecipitator declaring ``feed_1`` for type checkers."""

        feed_1: Port

    class ElectrostaticPrecipitator2(ElectrostaticPrecipitator):
        """ElectrostaticPrecipitator declaring ``feed_1`` to ``feed_2`` for type checkers."""

        feed_1: Port
        feed_2: Port

    class ElectrostaticPrecipitator3(ElectrostaticPrecipitator):
        """ElectrostaticPrecipitator declaring ``feed_1`` to ``feed_3`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port

    class ElectrostaticPrecipitator4(ElectrostaticPrecipitator):
        """ElectrostaticPrecipitator declaring ``feed_1`` to ``feed_4`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port

    class ElectrostaticPrecipitator5(ElectrostaticPrecipitator):
        """ElectrostaticPrecipitator declaring ``feed_1`` to ``feed_5`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port

    class ElectrostaticPrecipitator6(ElectrostaticPrecipitator):
        """ElectrostaticPrecipitator declaring ``feed_1`` to ``feed_6`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port

    class ElectrostaticPrecipitator7(ElectrostaticPrecipitator):
        """ElectrostaticPrecipitator declaring ``feed_1`` to ``feed_7`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port
        feed_7: Port

    class ElectrostaticPrecipitator8(ElectrostaticPrecipitator):
        """ElectrostaticPrecipitator declaring ``feed_1`` to ``feed_8`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port
        feed_7: Port
        feed_8: Port


class Screen(Separator):
    """Screen: a deck sorting by size, oversize over and fines through.

    Named ``Screen`` rather than ``Sifter`` because that is the word a
    specification uses. One drawing covers scalping and sizing; the ports
    name positions because either draw may be the product.

    Parameters are those of :class:`~pandid.units.Separator`.
    """

    kind = "separator"
    VARIANTS = ("default", "sifter")
    VARIANT_ALIASES = {"default": "sifter"}
    PORTS = [("overflow", "outlet", "process"), ("underflow", "outlet", "process")]

    overflow: Port
    underflow: Port

    if TYPE_CHECKING:

        @overload
        def __new__(cls, name: str, n_feeds: Literal[1] = 1,
                    *args: Any, **kwargs: Any) -> "Screen1": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[2],
                    *args: Any, **kwargs: Any) -> "Screen2": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[3],
                    *args: Any, **kwargs: Any) -> "Screen3": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[4],
                    *args: Any, **kwargs: Any) -> "Screen4": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[5],
                    *args: Any, **kwargs: Any) -> "Screen5": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[6],
                    *args: Any, **kwargs: Any) -> "Screen6": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[7],
                    *args: Any, **kwargs: Any) -> "Screen7": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[8],
                    *args: Any, **kwargs: Any) -> "Screen8": ...

        @overload
        def __new__(cls, name: str, n_feeds: int,
                    *args: Any, **kwargs: Any) -> "Screen": ...
        def __new__(cls, name: str, n_feeds: int = 1,
                    *args: Any, **kwargs: Any) -> "Screen": ...


if TYPE_CHECKING:

    class Screen1(Screen):
        """Screen declaring ``feed_1`` for type checkers."""

        feed_1: Port

    class Screen2(Screen):
        """Screen declaring ``feed_1`` to ``feed_2`` for type checkers."""

        feed_1: Port
        feed_2: Port

    class Screen3(Screen):
        """Screen declaring ``feed_1`` to ``feed_3`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port

    class Screen4(Screen):
        """Screen declaring ``feed_1`` to ``feed_4`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port

    class Screen5(Screen):
        """Screen declaring ``feed_1`` to ``feed_5`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port

    class Screen6(Screen):
        """Screen declaring ``feed_1`` to ``feed_6`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port

    class Screen7(Screen):
        """Screen declaring ``feed_1`` to ``feed_7`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port
        feed_7: Port

    class Screen8(Screen):
        """Screen declaring ``feed_1`` to ``feed_8`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port
        feed_7: Port
        feed_8: Port


class ImpactSeparator(Separator):
    """Impact separator: a baffle to throw the stream at.

    The knock-out on a pneumatic conveying line or a vent, where the
    heavy fraction cannot follow the gas round the baffle.

    Parameters are those of :class:`~pandid.units.Separator`.
    """

    kind = "separator"
    VARIANTS = ("default", "impact")
    VARIANT_ALIASES = {"default": "impact"}
    PORTS = [("overflow", "outlet", "process"), ("underflow", "outlet", "process")]

    overflow: Port
    underflow: Port

    if TYPE_CHECKING:

        @overload
        def __new__(cls, name: str, n_feeds: Literal[1] = 1,
                    *args: Any, **kwargs: Any) -> "ImpactSeparator1": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[2],
                    *args: Any, **kwargs: Any) -> "ImpactSeparator2": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[3],
                    *args: Any, **kwargs: Any) -> "ImpactSeparator3": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[4],
                    *args: Any, **kwargs: Any) -> "ImpactSeparator4": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[5],
                    *args: Any, **kwargs: Any) -> "ImpactSeparator5": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[6],
                    *args: Any, **kwargs: Any) -> "ImpactSeparator6": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[7],
                    *args: Any, **kwargs: Any) -> "ImpactSeparator7": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[8],
                    *args: Any, **kwargs: Any) -> "ImpactSeparator8": ...

        @overload
        def __new__(cls, name: str, n_feeds: int,
                    *args: Any, **kwargs: Any) -> "ImpactSeparator": ...
        def __new__(cls, name: str, n_feeds: int = 1,
                    *args: Any, **kwargs: Any) -> "ImpactSeparator": ...


if TYPE_CHECKING:

    class ImpactSeparator1(ImpactSeparator):
        """ImpactSeparator declaring ``feed_1`` for type checkers."""

        feed_1: Port

    class ImpactSeparator2(ImpactSeparator):
        """ImpactSeparator declaring ``feed_1`` to ``feed_2`` for type checkers."""

        feed_1: Port
        feed_2: Port

    class ImpactSeparator3(ImpactSeparator):
        """ImpactSeparator declaring ``feed_1`` to ``feed_3`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port

    class ImpactSeparator4(ImpactSeparator):
        """ImpactSeparator declaring ``feed_1`` to ``feed_4`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port

    class ImpactSeparator5(ImpactSeparator):
        """ImpactSeparator declaring ``feed_1`` to ``feed_5`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port

    class ImpactSeparator6(ImpactSeparator):
        """ImpactSeparator declaring ``feed_1`` to ``feed_6`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port

    class ImpactSeparator7(ImpactSeparator):
        """ImpactSeparator declaring ``feed_1`` to ``feed_7`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port
        feed_7: Port

    class ImpactSeparator8(ImpactSeparator):
        """ImpactSeparator declaring ``feed_1`` to ``feed_8`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port
        feed_7: Port
        feed_8: Port


class MagneticSeparator(Separator):
    """Magnetic separator: tramp metal pulled out of a solids stream.

    One class over both drawings: a **permanent** magnet (``default``)
    and an **electromagnet** (``electromagnetic``) differ only in how the
    field is made, with the same body and draws.

    Parameters are those of :class:`~pandid.units.Separator`.
    """

    kind = "separator"
    VARIANTS = ("default", "electromagnetic", "permanent_magnet")
    VARIANT_ALIASES = {"default": "permanent_magnet"}
    PORTS = [("overflow", "outlet", "process"), ("underflow", "outlet", "process")]

    overflow: Port
    underflow: Port

    if TYPE_CHECKING:

        @overload
        def __new__(cls, name: str, n_feeds: Literal[1] = 1,
                    *args: Any, **kwargs: Any) -> "MagneticSeparator1": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[2],
                    *args: Any, **kwargs: Any) -> "MagneticSeparator2": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[3],
                    *args: Any, **kwargs: Any) -> "MagneticSeparator3": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[4],
                    *args: Any, **kwargs: Any) -> "MagneticSeparator4": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[5],
                    *args: Any, **kwargs: Any) -> "MagneticSeparator5": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[6],
                    *args: Any, **kwargs: Any) -> "MagneticSeparator6": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[7],
                    *args: Any, **kwargs: Any) -> "MagneticSeparator7": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[8],
                    *args: Any, **kwargs: Any) -> "MagneticSeparator8": ...

        @overload
        def __new__(cls, name: str, n_feeds: int,
                    *args: Any, **kwargs: Any) -> "MagneticSeparator": ...
        def __new__(cls, name: str, n_feeds: int = 1,
                    *args: Any, **kwargs: Any) -> "MagneticSeparator": ...


if TYPE_CHECKING:

    class MagneticSeparator1(MagneticSeparator):
        """MagneticSeparator declaring ``feed_1`` for type checkers."""

        feed_1: Port

    class MagneticSeparator2(MagneticSeparator):
        """MagneticSeparator declaring ``feed_1`` to ``feed_2`` for type checkers."""

        feed_1: Port
        feed_2: Port

    class MagneticSeparator3(MagneticSeparator):
        """MagneticSeparator declaring ``feed_1`` to ``feed_3`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port

    class MagneticSeparator4(MagneticSeparator):
        """MagneticSeparator declaring ``feed_1`` to ``feed_4`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port

    class MagneticSeparator5(MagneticSeparator):
        """MagneticSeparator declaring ``feed_1`` to ``feed_5`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port

    class MagneticSeparator6(MagneticSeparator):
        """MagneticSeparator declaring ``feed_1`` to ``feed_6`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port

    class MagneticSeparator7(MagneticSeparator):
        """MagneticSeparator declaring ``feed_1`` to ``feed_7`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port
        feed_7: Port

    class MagneticSeparator8(MagneticSeparator):
        """MagneticSeparator declaring ``feed_1`` to ``feed_8`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port
        feed_7: Port
        feed_8: Port


class Scrubber(Separator):
    """Wet scrubber: a wash liquid takes the contaminant out of a gas.

    Cleaned gas leaves the side and dirty liquid the hopper, a true
    vapour and liquid, so unlike the dust collectors it keeps ``vapor``
    and ``liquid``.

    Parameters are those of :class:`~pandid.units.Separator`.
    """

    kind = "separator"
    VARIANTS = ("default", "scrubber")
    VARIANT_ALIASES = {"default": "scrubber"}
    PORTS = [("vapor", "outlet", "vapor"), ("liquid", "outlet", "liquid")]

    vapor: Port
    liquid: Port

    if TYPE_CHECKING:

        @overload
        def __new__(cls, name: str, n_feeds: Literal[1] = 1,
                    *args: Any, **kwargs: Any) -> "Scrubber1": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[2],
                    *args: Any, **kwargs: Any) -> "Scrubber2": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[3],
                    *args: Any, **kwargs: Any) -> "Scrubber3": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[4],
                    *args: Any, **kwargs: Any) -> "Scrubber4": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[5],
                    *args: Any, **kwargs: Any) -> "Scrubber5": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[6],
                    *args: Any, **kwargs: Any) -> "Scrubber6": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[7],
                    *args: Any, **kwargs: Any) -> "Scrubber7": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[8],
                    *args: Any, **kwargs: Any) -> "Scrubber8": ...

        @overload
        def __new__(cls, name: str, n_feeds: int,
                    *args: Any, **kwargs: Any) -> "Scrubber": ...
        def __new__(cls, name: str, n_feeds: int = 1,
                    *args: Any, **kwargs: Any) -> "Scrubber": ...


if TYPE_CHECKING:

    class Scrubber1(Scrubber):
        """Scrubber declaring ``feed_1`` for type checkers."""

        feed_1: Port

    class Scrubber2(Scrubber):
        """Scrubber declaring ``feed_1`` to ``feed_2`` for type checkers."""

        feed_1: Port
        feed_2: Port

    class Scrubber3(Scrubber):
        """Scrubber declaring ``feed_1`` to ``feed_3`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port

    class Scrubber4(Scrubber):
        """Scrubber declaring ``feed_1`` to ``feed_4`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port

    class Scrubber5(Scrubber):
        """Scrubber declaring ``feed_1`` to ``feed_5`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port

    class Scrubber6(Scrubber):
        """Scrubber declaring ``feed_1`` to ``feed_6`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port

    class Scrubber7(Scrubber):
        """Scrubber declaring ``feed_1`` to ``feed_7`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port
        feed_7: Port

    class Scrubber8(Scrubber):
        """Scrubber declaring ``feed_1`` to ``feed_8`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port
        feed_7: Port
        feed_8: Port


class VenturiScrubber(Separator):
    """Venturi scrubber: the wash is injected into an accelerating throat.

    A different mechanism from :class:`Scrubber`, so its own class: the
    gas is accelerated through a throat, which buys collection
    efficiency at the cost of pressure drop. The throat runs downward, so
    the feed is on the top.

    Parameters are those of :class:`~pandid.units.Separator`.
    """

    kind = "separator"
    VARIANTS = ("default", "venturi_scrubber")
    VARIANT_ALIASES = {"default": "venturi_scrubber"}
    PORTS = [("vapor", "outlet", "vapor"), ("liquid", "outlet", "liquid")]

    vapor: Port
    liquid: Port

    if TYPE_CHECKING:

        @overload
        def __new__(cls, name: str, n_feeds: Literal[1] = 1,
                    *args: Any, **kwargs: Any) -> "VenturiScrubber1": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[2],
                    *args: Any, **kwargs: Any) -> "VenturiScrubber2": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[3],
                    *args: Any, **kwargs: Any) -> "VenturiScrubber3": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[4],
                    *args: Any, **kwargs: Any) -> "VenturiScrubber4": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[5],
                    *args: Any, **kwargs: Any) -> "VenturiScrubber5": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[6],
                    *args: Any, **kwargs: Any) -> "VenturiScrubber6": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[7],
                    *args: Any, **kwargs: Any) -> "VenturiScrubber7": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[8],
                    *args: Any, **kwargs: Any) -> "VenturiScrubber8": ...

        @overload
        def __new__(cls, name: str, n_feeds: int,
                    *args: Any, **kwargs: Any) -> "VenturiScrubber": ...
        def __new__(cls, name: str, n_feeds: int = 1,
                    *args: Any, **kwargs: Any) -> "VenturiScrubber": ...


if TYPE_CHECKING:

    class VenturiScrubber1(VenturiScrubber):
        """VenturiScrubber declaring ``feed_1`` for type checkers."""

        feed_1: Port

    class VenturiScrubber2(VenturiScrubber):
        """VenturiScrubber declaring ``feed_1`` to ``feed_2`` for type checkers."""

        feed_1: Port
        feed_2: Port

    class VenturiScrubber3(VenturiScrubber):
        """VenturiScrubber declaring ``feed_1`` to ``feed_3`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port

    class VenturiScrubber4(VenturiScrubber):
        """VenturiScrubber declaring ``feed_1`` to ``feed_4`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port

    class VenturiScrubber5(VenturiScrubber):
        """VenturiScrubber declaring ``feed_1`` to ``feed_5`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port

    class VenturiScrubber6(VenturiScrubber):
        """VenturiScrubber declaring ``feed_1`` to ``feed_6`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port

    class VenturiScrubber7(VenturiScrubber):
        """VenturiScrubber declaring ``feed_1`` to ``feed_7`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port
        feed_7: Port

    class VenturiScrubber8(VenturiScrubber):
        """VenturiScrubber declaring ``feed_1`` to ``feed_8`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port
        feed_7: Port
        feed_8: Port


class KnockoutDrum(Separator):
    """Knock-out drum: an upright drum with a demister pad.

    A class despite the rule (drawn internals are variants) because
    "knock-out drum" is the term P&IDs, datasheets and searches use.

    The level gauge is drawn, not declared, so a level instrument added
    with :meth:`~pandid.flowsheet.Flowsheet.add_instrument` draws its own
    balloon beside it.

    Parameters are those of :class:`~pandid.units.Separator`.
    """

    kind = "separator"
    VARIANTS = ("default", "knockout")
    VARIANT_ALIASES = {"default": "knockout"}
    PORTS = [("vapor", "outlet", "vapor"), ("liquid", "outlet", "liquid")]

    vapor: Port
    liquid: Port

    if TYPE_CHECKING:

        @overload
        def __new__(cls, name: str, n_feeds: Literal[1] = 1,
                    *args: Any, **kwargs: Any) -> "KnockoutDrum1": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[2],
                    *args: Any, **kwargs: Any) -> "KnockoutDrum2": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[3],
                    *args: Any, **kwargs: Any) -> "KnockoutDrum3": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[4],
                    *args: Any, **kwargs: Any) -> "KnockoutDrum4": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[5],
                    *args: Any, **kwargs: Any) -> "KnockoutDrum5": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[6],
                    *args: Any, **kwargs: Any) -> "KnockoutDrum6": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[7],
                    *args: Any, **kwargs: Any) -> "KnockoutDrum7": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[8],
                    *args: Any, **kwargs: Any) -> "KnockoutDrum8": ...

        @overload
        def __new__(cls, name: str, n_feeds: int,
                    *args: Any, **kwargs: Any) -> "KnockoutDrum": ...
        def __new__(cls, name: str, n_feeds: int = 1,
                    *args: Any, **kwargs: Any) -> "KnockoutDrum": ...


if TYPE_CHECKING:

    class KnockoutDrum1(KnockoutDrum):
        """KnockoutDrum declaring ``feed_1`` for type checkers."""

        feed_1: Port

    class KnockoutDrum2(KnockoutDrum):
        """KnockoutDrum declaring ``feed_1`` to ``feed_2`` for type checkers."""

        feed_1: Port
        feed_2: Port

    class KnockoutDrum3(KnockoutDrum):
        """KnockoutDrum declaring ``feed_1`` to ``feed_3`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port

    class KnockoutDrum4(KnockoutDrum):
        """KnockoutDrum declaring ``feed_1`` to ``feed_4`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port

    class KnockoutDrum5(KnockoutDrum):
        """KnockoutDrum declaring ``feed_1`` to ``feed_5`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port

    class KnockoutDrum6(KnockoutDrum):
        """KnockoutDrum declaring ``feed_1`` to ``feed_6`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port

    class KnockoutDrum7(KnockoutDrum):
        """KnockoutDrum declaring ``feed_1`` to ``feed_7`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port
        feed_7: Port

    class KnockoutDrum8(KnockoutDrum):
        """KnockoutDrum declaring ``feed_1`` to ``feed_8`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port
        feed_7: Port
        feed_8: Port


class DustCollector(Filter):
    """Dust collector: a gas filter with a hopper under the medium.

    One class over the three gas casings, since the choice is the
    medium and all are piped alike: bag, candle or cartridge elements
    (``default``), a granular bed (``fixed_bed``) and a cloth on rollers
    (``belt``). Also known as a baghouse.

    Parameters are those of :class:`~pandid.units.Filter`.
    """

    kind = "filter"
    VARIANTS = ("default", "fixed_bed", "belt", "gas", "gas_fixed_bed", "gas_belt")
    VARIANT_ALIASES = {"default": "gas", "fixed_bed": "gas_fixed_bed", "belt": "gas_belt"}
    PORTS = [("inlet", "inlet", "process"), ("outlet", "outlet", "process")]

    inlet: Port
    outlet: Port


class RotaryDrumFilter(Filter):
    """Rotary drum filter: a drum turns through slurry under vacuum.

    Cake builds on the submerged face and is lifted off at the top. The
    ``scraper`` variant draws the knife that lifts it.

    ``inlet`` is the slurry, ``outlet`` the filtrate, ``cake`` what is
    lifted off, and ``wash_in`` the sprays that displace mother liquor
    first. Both variants have the same ports in the same places.

    Parameters are those of :class:`~pandid.units.Filter`.
    """

    kind = "filter"
    VARIANTS = ("default", "scraper", "rotary", "rotary_scraper")
    VARIANT_ALIASES = {"default": "rotary", "scraper": "rotary_scraper"}
    PORTS = [
        ("inlet", "inlet", "process"),
        ("wash_in", "inlet", "utility"),
        ("outlet", "outlet", "process"),
        ("cake", "outlet", "process"),
    ]

    inlet: Port
    wash_in: Port
    outlet: Port
    cake: Port


class FilterPress(Filter):
    """Filter press: plates squeezed together, slurry in, two products out.

    A batch machine on a continuous sheet. ``outlet`` is the filtrate and
    ``cake`` what the plates hold, often the product. ``wash_in`` is the
    displacement wash applied before the press opens.

    Parameters are those of :class:`~pandid.units.Filter`.
    """

    kind = "filter"
    VARIANTS = ("default", "press")
    VARIANT_ALIASES = {"default": "press"}
    PORTS = [
        ("inlet", "inlet", "process"),
        ("wash_in", "inlet", "utility"),
        ("outlet", "outlet", "process"),
        ("cake", "outlet", "process"),
    ]

    inlet: Port
    wash_in: Port
    outlet: Port
    cake: Port


class IonExchanger(Filter):
    """Ion exchanger: a resin bed between two retention screens.

    The vessel of a demineraliser or softener train; it removes
    dissolved rather than suspended matter. ``regenerant_in`` (acid,
    caustic or brine, above the bed) and ``spent_regenerant`` (out of the
    underdrain) replace the cake filters' wash and cake.

    Parameters are those of :class:`~pandid.units.Filter`.
    """

    kind = "filter"
    VARIANTS = ("default", "ion_exchange")
    VARIANT_ALIASES = {"default": "ion_exchange"}
    PORTS = [
        ("inlet", "inlet", "process"),
        ("regenerant_in", "inlet", "utility"),
        ("outlet", "outlet", "process"),
        ("spent_regenerant", "outlet", "process"),
    ]

    inlet: Port
    regenerant_in: Port
    outlet: Port
    spent_regenerant: Port


class RotaryDryer(Dryer):
    """Rotary drum dryer: a turning drum with hot gas through it.

    The bulk-solids dryer, and what ``Dryer`` draws when it is asked for
    by name.

    Parameters are those of :class:`~pandid.units.Dryer`.
    """

    kind = "dryer"
    VARIANTS = ("default",)
    PORTS = [
        ("feed", "inlet", "feed"),
        ("product", "outlet", "process"),
        ("heating_in", "inlet", "utility"),
        ("vent", "outlet", "vapor"),
    ]

    feed: Port
    product: Port
    heating_in: Port
    vent: Port


class FluidizedBedDryer(Dryer):
    """Fluidised-bed dryer: gas up through a distributor holds the bed.

    Even temperature and a high transfer rate, at the price of a bed
    that has to stay fluidised. The bed is a layer on its plate, so the
    symbol is one gravity fixes the attitude of.

    Parameters are those of :class:`~pandid.units.Dryer`.
    """

    kind = "dryer"
    VARIANTS = ("default", "fluidized_bed")
    VARIANT_ALIASES = {"default": "fluidized_bed"}
    PORTS = [
        ("feed", "inlet", "feed"),
        ("product", "outlet", "process"),
        ("heating_in", "inlet", "utility"),
        ("vent", "outlet", "vapor"),
    ]

    feed: Port
    product: Port
    heating_in: Port
    vent: Port


class SprayDryer(Dryer):
    """Spray dryer: feed atomised into hot gas, powder off the floor.

    Fed through the atomiser in its roof and drawn top to bottom rather
    than across, which is why the artwork must not be turned. The
    cyclone downstream of one is where the product is usually recovered;
    see :class:`Cyclone`.

    Parameters are those of :class:`~pandid.units.Dryer`.
    """

    kind = "dryer"
    VARIANTS = ("default", "spray")
    VARIANT_ALIASES = {"default": "spray"}
    PORTS = [
        ("feed", "inlet", "feed"),
        ("product", "outlet", "process"),
        ("heating_in", "inlet", "utility"),
        ("vent", "outlet", "vapor"),
    ]

    feed: Port
    product: Port
    heating_in: Port
    vent: Port


class ShelfDryer(Dryer):
    """Shelf (tray) dryer: trays of product in a heated oven or chamber.

    ISO 10628-2 item 10.2, X8083: the general drier's own casing
    carrying three shelf lines. Batch duty -- the trays are loaded and
    struck by hand -- next to the continuous machines the rest of the
    group draws.

    Parameters are those of :class:`~pandid.units.Dryer`.
    """

    kind = "dryer"
    VARIANTS = ("default", "shelf")
    VARIANT_ALIASES = {"default": "shelf"}
    PORTS = [
        ("feed", "inlet", "feed"),
        ("product", "outlet", "process"),
        ("heating_in", "inlet", "utility"),
        ("vent", "outlet", "vapor"),
    ]

    feed: Port
    product: Port
    heating_in: Port
    vent: Port


class TurboDryer(Dryer):
    """Turbo (disc, moving-shelf) dryer: a stack of rotating discs on one shaft.

    ISO 10628-2 item 10.3, X8040. The product moves down the stack from
    disc to disc as each one turns under it, which is what tells this
    from :class:`ShelfDryer`'s fixed trays -- the artwork's own shaft
    reaching to the casing's crown is the drive that turns them.

    Parameters are those of :class:`~pandid.units.Dryer`.
    """

    kind = "dryer"
    VARIANTS = ("default", "turbo")
    VARIANT_ALIASES = {"default": "turbo"}
    PORTS = [
        ("feed", "inlet", "feed"),
        ("product", "outlet", "process"),
        ("heating_in", "inlet", "utility"),
        ("vent", "outlet", "vapor"),
    ]

    feed: Port
    product: Port
    heating_in: Port
    vent: Port


class BeltDryer(Dryer):
    """Belt (roller-conveyor) dryer: product carried through on a moving bed.

    ISO 10628-2 item 10.6, X8043. Continuous duty, drawn as the two
    rollers a belt runs on -- the same construction
    :class:`~pandid.units.Conveyor`'s belt variant draws, here inside a
    heated casing rather than in the open.

    Parameters are those of :class:`~pandid.units.Dryer`.
    """

    kind = "dryer"
    VARIANTS = ("default", "belt")
    VARIANT_ALIASES = {"default": "belt"}
    PORTS = [
        ("feed", "inlet", "feed"),
        ("product", "outlet", "process"),
        ("heating_in", "inlet", "utility"),
        ("vent", "outlet", "vapor"),
    ]

    feed: Port
    product: Port
    heating_in: Port
    vent: Port


class JawCrusher(Crusher):
    """Jaw crusher: a swing jaw worked by an eccentric.

    The primary crusher of a hard-rock circuit -- run-of-mine ore in at
    the top, one product size out of the bottom. ISO 10628-2 item 11.5
    X8047: the crusher body carrying item 29.9 C2036.

    Parameters are those of :class:`~pandid.units.Crusher`.
    """

    kind = "crusher"
    VARIANTS = ("default", "jaw")
    VARIANT_ALIASES = {"default": "jaw"}
    PORTS = [("feed", "inlet", "feed"), ("discharge", "outlet", "process")]

    feed: Port
    discharge: Port


class ConeCrusher(Crusher):
    """Cone crusher: a gyrating head inside a fixed bowl.

    Secondary and tertiary duty behind a jaw, and where a gyratory
    crusher is drawn too. ISO 10628-2 item 11.7 X8049: the crusher body
    carrying item 29.12 C2038.

    Parameters are those of :class:`~pandid.units.Crusher`.
    """

    kind = "crusher"
    VARIANTS = ("default", "cone")
    VARIANT_ALIASES = {"default": "cone"}
    PORTS = [("feed", "inlet", "feed"), ("discharge", "outlet", "process")]

    feed: Port
    discharge: Port


class HammerCrusher(Crusher):
    """Hammer crusher: swing hammers on a rotor, against a breaker plate.

    For friable and medium-hard feed -- limestone, gypsum, coal. ISO
    10628-2 item 11.3 X8045: the crusher body carrying item 29.7 C2034.

    Parameters are those of :class:`~pandid.units.Crusher`.
    """

    kind = "crusher"
    VARIANTS = ("default", "hammer")
    VARIANT_ALIASES = {"default": "hammer"}
    PORTS = [("feed", "inlet", "feed"), ("discharge", "outlet", "process")]

    feed: Port
    discharge: Port


class ImpactCrusher(Crusher):
    """Impact crusher: blow bars on a rotor throwing feed at aprons.

    Breaks on impact rather than by compression, so it makes a cubical
    product and more fines than a jaw. ISO 10628-2 item 11.4 X8046: the
    crusher body carrying item 29.8 C2035.

    Parameters are those of :class:`~pandid.units.Crusher`.
    """

    kind = "crusher"
    VARIANTS = ("default", "impact")
    VARIANT_ALIASES = {"default": "impact"}
    PORTS = [("feed", "inlet", "feed"), ("discharge", "outlet", "process")]

    feed: Port
    discharge: Port


class RollerCrusher(Crusher):
    """Roll crusher: two counter-rotating rolls with a nip between them.

    A closely sized product from a friable feed, and the sizer of a coal
    or bauxite circuit. ISO 10628-2 item 11.6 X8048: the crusher body
    carrying item 29.11 C2037.

    Parameters are those of :class:`~pandid.units.Crusher`.
    """

    kind = "crusher"
    VARIANTS = ("default", "roller")
    VARIANT_ALIASES = {"default": "roller"}
    PORTS = [("feed", "inlet", "feed"), ("discharge", "outlet", "process")]

    feed: Port
    discharge: Port


class HammerMill(Mill):
    """Hammer mill: swing hammers against a screen.

    The same hammers as a hammer crusher in a machine ground for a
    finer product, which is the whole difference ISO draws between the
    two bodies. Item 11.9 X8050: the mill body carrying item 29.7 C2034.

    Parameters are those of :class:`~pandid.units.Mill`.
    """

    kind = "mill"
    VARIANTS = ("default", "hammer")
    VARIANT_ALIASES = {"default": "hammer"}
    PORTS = [("feed", "inlet", "feed"), ("discharge", "outlet", "process")]

    feed: Port
    discharge: Port


class ImpactMill(Mill):
    """Impact mill, pin mill: a rotor throwing feed at a liner.

    Fine grinding of soft and friable solids. ISO 10628-2 item 11.10
    X8051: the mill body carrying item 29.8 C2035.

    Parameters are those of :class:`~pandid.units.Mill`.
    """

    kind = "mill"
    VARIANTS = ("default", "impact")
    VARIANT_ALIASES = {"default": "impact"}
    PORTS = [("feed", "inlet", "feed"), ("discharge", "outlet", "process")]

    feed: Port
    discharge: Port


class RollerMill(Mill):
    """Roller mill: rolls running on a table or against a ring.

    The horizontal-rotation roller mill of a cement or coal circuit.
    ISO 10628-2 item 11.11 X8053: the mill body carrying item 29.11
    C2037.

    Parameters are those of :class:`~pandid.units.Mill`.
    """

    kind = "mill"
    VARIANTS = ("default", "roller")
    VARIANT_ALIASES = {"default": "roller"}
    PORTS = [("feed", "inlet", "feed"), ("discharge", "outlet", "process")]

    feed: Port
    discharge: Port


class VibratingMill(Mill):
    """Vibrating mill: a charged drum shaken rather than tumbled.

    Fine and ultrafine grinding in a small footprint. ISO 10628-2 item
    11.12 X8054, and the one group-11 row that is not a body and a mark
    alone: the drawing puts the two arrows of item 29.14 (3831) inside a
    drum the standard gives no number of its own, so the drum is drawn
    as part of the body. See
    ``pandid.render.symbols._VIBRATION_DRUM``.

    Parameters are those of :class:`~pandid.units.Mill`.
    """

    kind = "mill"
    VARIANTS = ("default", "vibration")
    VARIANT_ALIASES = {"default": "vibration"}
    PORTS = [("feed", "inlet", "feed"), ("discharge", "outlet", "process")]

    feed: Port
    discharge: Port


class ScrewConveyor(Conveyor):
    """Screw conveyor: a flighted shaft turning in a closed trough.

    Short runs of dusty, hot or hazardous solids, where the enclosure
    is the point. Fed through a spout on top near the tail and
    discharged through one underneath near the head, which is where
    ISO 10628-2 item 18.5 X8063 draws its two connections.

    Sized by ``length=``, as every conveyor is; a longer trough gets
    more turns of the flight rather than a longer one.

    Parameters are those of :class:`~pandid.units.Conveyor`.
    """

    kind = "conveyor"
    VARIANTS = ("default", "screw")
    VARIANT_ALIASES = {"default": "screw"}
    PORTS = [("feed", "inlet", "feed"), ("discharge", "outlet", "process")]

    feed: Port
    discharge: Port


class RotaryValveFeeder(Feeder):
    """Rotary valve feeder: a close-fitting rotor metering solids through a housing.

    The standard way solids enter a pressurised system, one pocket of
    the rotor at a time -- a purge lock as much as a feeder. ISO
    10628-2 item 19.2 X8067.

    Parameters are those of :class:`~pandid.units.Feeder`.
    """

    kind = "feeder"
    VARIANTS = ("default", "rotary_valve")
    VARIANT_ALIASES = {"default": "rotary_valve"}
    PORTS = [("feed", "inlet", "feed"), ("discharge", "outlet", "process")]

    feed: Port
    discharge: Port


class RotaryTableFeeder(Feeder):
    """Rotary table feeder: solids dropped onto a turning table and ploughed off its edge.

    A steady, low-headroom feed off a hopper -- ISO 10628-2 item 19.3
    C0074 -- drawn as the table, its shaft and the rotation it turns
    on.

    Parameters are those of :class:`~pandid.units.Feeder`.
    """

    kind = "feeder"
    VARIANTS = ("default", "rotary_table")
    VARIANT_ALIASES = {"default": "rotary_table"}
    PORTS = [("feed", "inlet", "feed"), ("discharge", "outlet", "process")]

    feed: Port
    discharge: Port


class MeteringFeeder(Feeder):
    """Metering (weigh) feeder: solids let through in proportion to a measured weight.

    Drawn as a balance -- ISO 10628-2 item 19.4 C0035 -- because that
    is the principle: what leaves is metered against what the pans
    weigh, not against a timer or a gate position.

    Parameters are those of :class:`~pandid.units.Feeder`.
    """

    kind = "feeder"
    VARIANTS = ("default", "metering")
    VARIANT_ALIASES = {"default": "metering"}
    PORTS = [("feed", "inlet", "feed"), ("discharge", "outlet", "process")]

    feed: Port
    discharge: Port


class CoarseRakeScreen(ScreeningDevice):
    """Rake screen, coarse type: a mesh cleared by a coarse-toothed rake.

    ISO 10628-2 item 7.2 X8026.

    Parameters are those of :class:`~pandid.units.ScreeningDevice`.
    """

    kind = "screening_device"
    VARIANTS = ("default", "coarse_rake")
    VARIANT_ALIASES = {"default": "coarse_rake"}
    PORTS = [
        ("feed", "inlet", "feed"),
        ("oversize", "outlet", "process"),
        ("undersize", "outlet", "process"),
    ]

    feed: Port
    oversize: Port
    undersize: Port


class FineRakeScreen(ScreeningDevice):
    """Rake screen, fine type: the same rake at a finer tooth pitch.

    ISO 10628-2 item 7.3 X8027.

    Parameters are those of :class:`~pandid.units.ScreeningDevice`.
    """

    kind = "screening_device"
    VARIANTS = ("default", "fine_rake")
    VARIANT_ALIASES = {"default": "fine_rake"}
    PORTS = [
        ("feed", "inlet", "feed"),
        ("oversize", "outlet", "process"),
        ("undersize", "outlet", "process"),
    ]

    feed: Port
    oversize: Port
    undersize: Port


class CoarseAndFineScreen(ScreeningDevice):
    """Double-deck screen: a coarse deck over a fine one in one casing.

    ISO 10628-2 item 7.4 X8028: the two mesh lines Table 2 draws are
    the two decks, one screening pass each.

    Parameters are those of :class:`~pandid.units.ScreeningDevice`.
    """

    kind = "screening_device"
    VARIANTS = ("default", "coarse_and_fine")
    VARIANT_ALIASES = {"default": "coarse_and_fine"}
    PORTS = [
        ("feed", "inlet", "feed"),
        ("oversize", "outlet", "process"),
        ("undersize", "outlet", "process"),
    ]

    feed: Port
    oversize: Port
    undersize: Port


class VibratingScreen(ScreeningDevice):
    """Vibrating screen: the deck itself is shaken to work material across it.

    The screener a sizing or dewatering duty reaches for first. ISO
    10628-2 item 7.5 X2605, the same double-arrow oscillation mark
    :class:`VibratingMill` carries on its own drum.

    Parameters are those of :class:`~pandid.units.ScreeningDevice`.
    """

    kind = "screening_device"
    VARIANTS = ("default", "vibrating")
    VARIANT_ALIASES = {"default": "vibrating"}
    PORTS = [
        ("feed", "inlet", "feed"),
        ("oversize", "outlet", "process"),
        ("undersize", "outlet", "process"),
    ]

    feed: Port
    oversize: Port
    undersize: Port


class RotaryDrumScreen(ScreeningDevice):
    """Rotary drum screen, trommel: a slowly turning perforated cylinder.

    Coarse scalping ahead of a crusher, or dewatering off a wash
    circuit. ISO 10628-2 item 7.6 X8029.

    Parameters are those of :class:`~pandid.units.ScreeningDevice`.
    """

    kind = "screening_device"
    VARIANTS = ("default", "rotating_drum")
    VARIANT_ALIASES = {"default": "rotating_drum"}
    PORTS = [
        ("feed", "inlet", "feed"),
        ("oversize", "outlet", "process"),
        ("undersize", "outlet", "process"),
    ]

    feed: Port
    oversize: Port
    undersize: Port


class ReelScreen(ScreeningDevice):
    """Reel screen: a wire basket strung between two rollers and turned.

    ISO 10628-2 item 7.7 X8030, drawn in a taller outline than the
    other six rows to hold the reel's own rollers.

    Parameters are those of :class:`~pandid.units.ScreeningDevice`.
    """

    kind = "screening_device"
    VARIANTS = ("default", "basket_reel")
    VARIANT_ALIASES = {"default": "basket_reel"}
    PORTS = [
        ("feed", "inlet", "feed"),
        ("oversize", "outlet", "process"),
        ("undersize", "outlet", "process"),
    ]

    feed: Port
    oversize: Port
    undersize: Port


class ThreeWayValve(Valve):
    """Three-way valve: a third leg the run is switched between.

    The ISO three-port mark, with the third connection anchored as
    ``branch`` -- see :class:`~pandid.units.Valve` for what it is
    declared as and why.

    Parameters are those of :class:`~pandid.units.Valve`.
    """

    kind = "valve"
    VARIANTS = ("default", "three_way")
    VARIANT_ALIASES = {"default": "three_way"}
    PORTS = [
        ("inlet", "inlet", "process"),
        ("outlet", "outlet", "process"),
        ("actuator", "inlet", "signal"),
        ("branch", "outlet", "process"),
    ]

    inlet: Port
    outlet: Port
    actuator: Port
    branch: Port


class ControlValve(Valve):
    """Control valve: the final element a loop's output lands on.

    The valve a controller modulates. ISO 15519-2 Table A.3.20 is the
    general control valve with a general actuator; this draws the general
    body with A.3.41's diaphragm, the specific symbol Table 5 asks for on a
    P&ID (a PFD, per Table 4, would use the general one). The stencil set
    has no separate general actuator. ``butterfly_pneumatic`` is the same
    actuator on a butterfly disc, also reached as
    ``ControlValve(variant="butterfly", actuator="diaphragm")``.

    It usually declares ``fail=``. It may not be shown normally closed
    (PIP PIC001 4.2.2.10), since a darkened control valve reads as a closed
    block valve; use ``fail="closed"``.

    Parameters are those of :class:`~pandid.units.Valve`.
    """

    kind = "valve"
    VARIANTS = ("default", "butterfly_pneumatic", "control")
    VARIANT_ALIASES = {"default": "control"}
    PORTS = [
        ("inlet", "inlet", "process"),
        ("outlet", "outlet", "process"),
        ("actuator", "inlet", "signal"),
    ]

    inlet: Port
    outlet: Port
    actuator: Port


class SolenoidValve(Valve):
    """Solenoid valve: an electrically operated on/off valve.

    The valve a trip acts through, and the pilot on a larger actuator.
    On/off rather than modulating, so it takes a ``fail`` position and
    it may be shown normally closed, which is how a dump or a purge
    valve is drawn.

    Parameters are those of :class:`~pandid.units.Valve`.
    """

    kind = "valve"
    VARIANTS = ("default", "solenoid")
    VARIANT_ALIASES = {"default": "solenoid"}
    PORTS = [
        ("inlet", "inlet", "process"),
        ("outlet", "outlet", "process"),
        ("actuator", "inlet", "signal"),
    ]

    inlet: Port
    outlet: Port
    actuator: Port


class ReliefValve(Valve):
    """Pressure relief valve: it opens itself at the set pressure.

    The PSV/PRV a protected system is drawn with, in either of the two
    bodies the stencil set draws (``default`` is the bonnet-on-a-stem
    relief; ``psv`` is the spring-loaded angle body a real sheet draws).
    Worked by the process itself, so it has no actuating energy to lose
    and declares no ``fail``, and PIP PIC001 4.2.2.10 forbids showing it
    normally closed.

    Parameters are those of :class:`~pandid.units.Valve`.
    """

    kind = "valve"
    VARIANTS = ("default", "psv", "relief")
    VARIANT_ALIASES = {"default": "relief"}
    PORTS = [
        ("inlet", "inlet", "process"),
        ("outlet", "outlet", "process"),
        ("actuator", "inlet", "signal"),
    ]

    inlet: Port
    outlet: Port
    actuator: Port


class PressureRegulator(Valve):
    """Self-acting regulator: the process works its own diaphragm.

    A back-pressure or a reducing regulator, holding a pressure with no
    controller and no signal. Its "actuator" connection is the external
    pilot line rather than a signal terminus. No ``fail`` position for
    :class:`ReliefValve`'s reason, and no NC mark for the same clause.

    Parameters are those of :class:`~pandid.units.Valve`.
    """

    kind = "valve"
    VARIANTS = ("default", "regulator")
    VARIANT_ALIASES = {"default": "regulator"}
    PORTS = [
        ("inlet", "inlet", "process"),
        ("outlet", "outlet", "process"),
        ("actuator", "inlet", "signal"),
    ]

    inlet: Port
    outlet: Port
    actuator: Port


class MotorOperatedValve(Valve):
    """Motor-operated valve: a block valve on an electric actuator.

    Stroked open or shut from the control system rather than modulated,
    which is why it takes a ``fail`` position and, unlike a control
    valve, may be shown normally closed.

    Parameters are those of :class:`~pandid.units.Valve`.
    """

    kind = "valve"
    VARIANTS = ("default", "motor")
    VARIANT_ALIASES = {"default": "motor"}
    PORTS = [
        ("inlet", "inlet", "process"),
        ("outlet", "outlet", "process"),
        ("actuator", "inlet", "signal"),
    ]

    inlet: Port
    outlet: Port
    actuator: Port


class CheckValve(Valve):
    """Check valve: it passes flow one way and shuts against the other.

    Worked by the flow itself, so it has no ``actuator`` port and a
    signal line cannot be connected to it; that missing port is why it is
    a class.

    The arrow inside the outline would be hidden by a darkened body, so a
    normally closed one is marked ``NC`` beside it (PIP PIC001 4.2.2.8).

    Parameters are those of :class:`~pandid.units.Valve`.
    """

    kind = "valve"
    VARIANTS = ("default", "check")
    VARIANT_ALIASES = {"default": "check"}
    PORTS = [("inlet", "inlet", "process"), ("outlet", "outlet", "process")]

    inlet: Port
    outlet: Port


class SpectacleBlind(Fitting):
    """Spectacle blind: two discs on a tie, one bored and one solid.

    The fitting with a declarable property, which makes it a class. The
    stencil set draws both states:

    - ``normal_position="open"`` (the default) puts the **ring** in the
      line, with the solid disc parked above it: the line is through.
    - ``normal_position="closed"`` puts the **solid** disc in the line:
      blanked.

    Parameters are those of :class:`~pandid.units.Fitting`.
    """

    kind = "fitting"
    VARIANTS = ("default", "blind")
    VARIANT_ALIASES = {"default": "blind"}
    PORTS = [("inlet", "inlet", "process"), ("outlet", "outlet", "process")]

    inlet: Port
    outlet: Port


class SteamTrap(Fitting):
    """Steam trap: drains condensate from a steam line and holds the steam.

    ISO 10628-2 Table 2 item 24.15, registered 2181. Drawn as the row
    draws it: a body with a diameter across it at 45 degrees and the
    discharge half below that filled.

    A class rather than a :class:`~pandid.units.Fitting` style because a
    trap is scheduled and bought as its own item. Fitted at each low point
    and drip leg of a steam main; condensate passes to the return header or
    drain.

    Parameters are those of :class:`~pandid.units.Fitting`.
    """

    kind = "fitting"
    VARIANTS = ("default", "steam_trap")
    VARIANT_ALIASES = {"default": "steam_trap"}
    PORTS = [("inlet", "inlet", "process"), ("outlet", "outlet", "process")]

    inlet: Port
    outlet: Port


class FlowElement(Fitting):
    """Primary flow element: the device in the run an FE balloon reads.

    One class over the twelve the stencil set draws, because to the
    flowsheet they are the same thing -- a pair of faces on a line --
    and the choice between them is the metering principle: a
    differential-pressure profile (``default``/``venturi``,
    ``flow_nozzle``, ``v_cone``, ``wedge``, ``target``, ``pitot``,
    ``averaging_pitot``) or a meter body (``coriolis``, ``vortex``,
    ``ultrasonic``, ``turbine_meter``, ``positive_displacement``).

    A class rather than a ``Fitting`` style because it is listed on the
    instrument schedule. Attach the balloon with
    :meth:`~pandid.flowsheet.Flowsheet.add_instrument`. The restriction
    orifice (which restricts rather than measures) and the rotameter
    (which indicates itself) stay ``Fitting`` variants.

    Parameters are those of :class:`~pandid.units.Fitting`.
    """

    kind = "fitting"
    VARIANTS = (
        "default",
        "venturi",
        "flow_nozzle",
        "coriolis",
        "vortex",
        "ultrasonic",
        "turbine_meter",
        "positive_displacement",
        "v_cone",
        "wedge",
        "target",
        "pitot",
        "averaging_pitot",
    )
    VARIANT_ALIASES = {"default": "venturi"}
    PORTS = [("inlet", "inlet", "process"), ("outlet", "outlet", "process")]

    inlet: Port
    outlet: Port


class StirredTankReactor(Reactor):
    """Stirred-tank reactor: a charge vessel with a top agitator.

    A class despite the rule (an agitator is a drawn internal) because
    "stirred tank reactor" and "CSTR" are the terms engineers search for.

    ``n_feeds`` adds feed ports as on :class:`pandid.units.Reactor`.

    Parameters are those of :class:`~pandid.units.Reactor`.
    """

    kind = "reactor"
    VARIANTS = ("default",)
    PORTS = [
        ("outlet", "outlet", "process"),
        ("vent", "outlet", "vapor"),
        ("duty", "inlet", "energy"),
    ]

    outlet: Port
    vent: Port
    duty: Port

    if TYPE_CHECKING:

        @overload
        def __new__(cls, name: str, n_feeds: Literal[1] = 1,
                    *args: Any, **kwargs: Any) -> "StirredTankReactor1": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[2],
                    *args: Any, **kwargs: Any) -> "StirredTankReactor2": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[3],
                    *args: Any, **kwargs: Any) -> "StirredTankReactor3": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[4],
                    *args: Any, **kwargs: Any) -> "StirredTankReactor4": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[5],
                    *args: Any, **kwargs: Any) -> "StirredTankReactor5": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[6],
                    *args: Any, **kwargs: Any) -> "StirredTankReactor6": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[7],
                    *args: Any, **kwargs: Any) -> "StirredTankReactor7": ...

        @overload
        def __new__(cls, name: str, n_feeds: Literal[8],
                    *args: Any, **kwargs: Any) -> "StirredTankReactor8": ...

        @overload
        def __new__(cls, name: str, n_feeds: int,
                    *args: Any, **kwargs: Any) -> "StirredTankReactor": ...
        def __new__(cls, name: str, n_feeds: int = 1,
                    *args: Any, **kwargs: Any) -> "StirredTankReactor": ...


if TYPE_CHECKING:

    class StirredTankReactor1(StirredTankReactor):
        """StirredTankReactor declaring ``feed_1`` for type checkers."""

        feed_1: Port

    class StirredTankReactor2(StirredTankReactor):
        """StirredTankReactor declaring ``feed_1`` to ``feed_2`` for type checkers."""

        feed_1: Port
        feed_2: Port

    class StirredTankReactor3(StirredTankReactor):
        """StirredTankReactor declaring ``feed_1`` to ``feed_3`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port

    class StirredTankReactor4(StirredTankReactor):
        """StirredTankReactor declaring ``feed_1`` to ``feed_4`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port

    class StirredTankReactor5(StirredTankReactor):
        """StirredTankReactor declaring ``feed_1`` to ``feed_5`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port

    class StirredTankReactor6(StirredTankReactor):
        """StirredTankReactor declaring ``feed_1`` to ``feed_6`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port

    class StirredTankReactor7(StirredTankReactor):
        """StirredTankReactor declaring ``feed_1`` to ``feed_7`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port
        feed_7: Port

    class StirredTankReactor8(StirredTankReactor):
        """StirredTankReactor declaring ``feed_1`` to ``feed_8`` for type checkers."""

        feed_1: Port
        feed_2: Port
        feed_3: Port
        feed_4: Port
        feed_5: Port
        feed_6: Port
        feed_7: Port
        feed_8: Port


class GasHolder(Tank):
    """Gas holder: a bell floating in a water seal.

    The only tank drawing with a class: other tank variants are roofs,
    floors or shells of one atmospheric liquid tank, while a gas holder
    stores gas at constant pressure and variable volume, with a moving
    bell and a water seal.

    ``inlet`` and ``outlet`` are the gas main, on the seal tank, since the
    bell moves. ``vent`` and ``relief`` are the crown valves on the bell,
    discharging to atmosphere. ``drain`` is the seal water.

    Parameters are those of :class:`~pandid.units.Tank`.
    """

    kind = "tank"
    VARIANTS = ("default", "gas_holder")
    VARIANT_ALIASES = {"default": "gas_holder"}
    PORTS = [
        ("vent", "outlet", "vapor"),
        ("relief", "outlet", "process"),
        ("drain", "outlet", "liquid"),
    ]

    vent: Port
    relief: Port
    drain: Port

    if TYPE_CHECKING:

        @overload
        def __new__(cls, name: str, inputs: Literal[1] = 1,
                    *args: Any, **kwargs: Any) -> "GasHolder1": ...

        @overload
        def __new__(cls, name: str, inputs: Literal[2],
                    *args: Any, **kwargs: Any) -> "GasHolder2": ...

        @overload
        def __new__(cls, name: str, inputs: Literal[3],
                    *args: Any, **kwargs: Any) -> "GasHolder3": ...

        @overload
        def __new__(cls, name: str, inputs: Literal[4],
                    *args: Any, **kwargs: Any) -> "GasHolder4": ...

        @overload
        def __new__(cls, name: str, inputs: Literal[5],
                    *args: Any, **kwargs: Any) -> "GasHolder5": ...

        @overload
        def __new__(cls, name: str, inputs: Literal[6],
                    *args: Any, **kwargs: Any) -> "GasHolder6": ...

        @overload
        def __new__(cls, name: str, inputs: Literal[7],
                    *args: Any, **kwargs: Any) -> "GasHolder7": ...

        @overload
        def __new__(cls, name: str, inputs: Literal[8],
                    *args: Any, **kwargs: Any) -> "GasHolder8": ...

        @overload
        def __new__(cls, name: str, inputs: int,
                    *args: Any, **kwargs: Any) -> "GasHolder": ...
        def __new__(cls, name: str, inputs: int = 1,
                    *args: Any, **kwargs: Any) -> "GasHolder": ...


if TYPE_CHECKING:

    class GasHolder1(GasHolder):
        """GasHolder declaring ``in_1`` for type checkers."""

        in_1: Port

    class GasHolder2(GasHolder):
        """GasHolder declaring ``in_1`` to ``in_2`` for type checkers."""

        in_1: Port
        in_2: Port

    class GasHolder3(GasHolder):
        """GasHolder declaring ``in_1`` to ``in_3`` for type checkers."""

        in_1: Port
        in_2: Port
        in_3: Port

    class GasHolder4(GasHolder):
        """GasHolder declaring ``in_1`` to ``in_4`` for type checkers."""

        in_1: Port
        in_2: Port
        in_3: Port
        in_4: Port

    class GasHolder5(GasHolder):
        """GasHolder declaring ``in_1`` to ``in_5`` for type checkers."""

        in_1: Port
        in_2: Port
        in_3: Port
        in_4: Port
        in_5: Port

    class GasHolder6(GasHolder):
        """GasHolder declaring ``in_1`` to ``in_6`` for type checkers."""

        in_1: Port
        in_2: Port
        in_3: Port
        in_4: Port
        in_5: Port
        in_6: Port

    class GasHolder7(GasHolder):
        """GasHolder declaring ``in_1`` to ``in_7`` for type checkers."""

        in_1: Port
        in_2: Port
        in_3: Port
        in_4: Port
        in_5: Port
        in_6: Port
        in_7: Port

    class GasHolder8(GasHolder):
        """GasHolder declaring ``in_1`` to ``in_8`` for type checkers."""

        in_1: Port
        in_2: Port
        in_3: Port
        in_4: Port
        in_5: Port
        in_6: Port
        in_7: Port
        in_8: Port
