"""Equipment classes: what a piece of plant *is*, over the drawing it is made of.

GENERATED by scripts/gen_devices.py. Do not edit by hand.

:mod:`pandid.units` models equipment as a ``kind`` and a ``variant``, which is
what the symbol registry is keyed by and what a sheet is drawn from. This module
is the other half of that: one class per device the registry draws, so that

    * an engineer looking for a cyclone finds :class:`Cyclone`, rather than
      having to know that it is spelled ``Separator(variant="cyclone")``;
    * a type checker can answer ``cyclone.underflow``, because the nozzles are
      declared on the class instead of depending on a string;
    * an equipment list reads as equipment.

The rule the split follows is that **a class is what the equipment is and
``variant=`` is how it is drawn**: a variant becomes a class when it names a
distinct scheduled item, and stays a variant when it names a support, a roof, a
cladding, an attitude, a drawn internal, a certification rating or a body style.
So a gate valve and a ball valve are one class and two variants, while a check
valve is a class of its own -- it has no actuator, and that is a fact about the
device rather than about its picture.

The low-level form is not going anywhere. ``Separator(variant="cyclone")`` stays
supported indefinitely, and it is the only way to reach the ninety-odd drawings
that never get a class of their own; ``pandid.render.symbols.default_registry``
is still the whole catalogue.

**One drawing, one nozzle vocabulary.** :class:`Cyclone`,
:class:`GravitySeparator` and :class:`ElectrostaticPrecipitator` collect *dust*,
and their drawings have anchored the catch ``liquid`` since 0.1.0. All three
classes call it ``underflow``, and the gas draw ``overflow``, which is what
classification and solid-liquid separation call them and what the sibling
mechanical separators already ship with.

Up to 0.1.1 ``Separator(variant="cyclone")`` kept ``vapor``/``liquid``, and this
docstring recorded the split as the permanent cost of correcting the names
without a break: one drawing answering to two vocabularies, and which you got
depended on which class you constructed. As of 0.1.2 it does not. The low-level
form draws ``overflow`` and ``underflow`` too, the old pair resolves for one
release with a :class:`DeprecationWarning` and a ``deprecated`` finding on
``fs.validate()``, and it is gone in 0.1.3. The artwork is untouched throughout:
the anchors it shipped with are mapped in
:attr:`pandid.units.Separator._VARIANT_ANCHORS`, which is why nothing on any
sheet moved.

Not star-imported into :mod:`pandid.units`: this module imports its bases from
there, so that would be a genuine cycle. ``from pandid import devices``, or take
the names off the package, which re-exports them all.
"""

from pandid.ports import Port
from pandid.units import (
    Compressor,
    Dryer,
    Filter,
    Fitting,
    HeatExchanger,
    Pump,
    Reactor,
    Separator,
    Valve,
)

__all__ = [
    "CentrifugalPump",
    "GearPump",
    "ScrewPump",
    "PeristalticPump",
    "SubmersiblePump",
    "VacuumPump",
    "CentrifugalCompressor",
    "ReciprocatingCompressor",
    "RotaryCompressor",
    "LiquidRingCompressor",
    "ShellAndTubeExchanger",
    "DoublePipeExchanger",
    "KettleReboiler",
    "Condenser",
    "AirCooledExchanger",
    "PlateExchanger",
    "SpiralExchanger",
    "ThinFilmEvaporator",
    "Cyclone",
    "GravitySeparator",
    "ElectrostaticPrecipitator",
    "Screen",
    "ImpactSeparator",
    "MagneticSeparator",
    "Scrubber",
    "KnockoutDrum",
    "DustCollector",
    "RotaryDrumFilter",
    "FilterPress",
    "IonExchanger",
    "RotaryDryer",
    "FluidizedBedDryer",
    "SprayDryer",
    "ControlValve",
    "SolenoidValve",
    "ReliefValve",
    "PressureRegulator",
    "MotorOperatedValve",
    "CheckValve",
    "SpectacleBlind",
    "FlowElement",
    "StirredTankReactor",
]


class CentrifugalPump(Pump):
    """Centrifugal pump: the volute-and-impeller machine most process duty runs on.

    What ``Pump`` draws when it is asked for by name, under the name a schedule
    calls it. Head falls as flow rises, so it throttles on a control valve
    rather than on a relief; contrast :class:`GearPump` and :class:`ScrewPump`,
    which are positive displacement and do not.
    """

    kind = "pump"
    VARIANTS = ("default",)
    PORTS = [("suction", "inlet", "process"), ("discharge", "outlet", "process")]

    suction: Port
    discharge: Port


class GearPump(Pump):
    """Gear pump: positive displacement, for viscous or metered duty.

    Two meshing gears carry fluid round the casing, so flow is set by speed and
    is very nearly independent of discharge pressure. That is why a positive
    displacement pump is protected by a relief valve and a centrifugal is not:
    a closed discharge has nowhere to go.
    """

    kind = "pump"
    VARIANTS = ("default", "gear")
    VARIANT_ALIASES = {"default": "gear"}
    PORTS = [("suction", "inlet", "process"), ("discharge", "outlet", "process")]

    suction: Port
    discharge: Port


class ScrewPump(Pump):
    """Screw pump: positive displacement, for viscous, shear-sensitive duty.

    One or more screws in a close-fitting barrel, moving a smooth, pulsation-free
    flow along the axis. The same relief-valve rule as :class:`GearPump`.
    """

    kind = "pump"
    VARIANTS = ("default", "screw")
    VARIANT_ALIASES = {"default": "screw"}
    PORTS = [("suction", "inlet", "process"), ("discharge", "outlet", "process")]

    suction: Port
    discharge: Port


class PeristalticPump(Pump):
    """Peristaltic (hose) pump: rollers squeeze a tube, so nothing wets the pump.

    The metering pump for a slurry or a reagent that must not meet a seal or an
    impeller: the fluid touches the hose and nothing else. Both connections
    leave the top of the head, which is where the stencil draws the tube.
    """

    kind = "pump"
    VARIANTS = ("default", "peristaltic")
    VARIANT_ALIASES = {"default": "peristaltic"}
    PORTS = [("suction", "inlet", "process"), ("discharge", "outlet", "process")]

    suction: Port
    discharge: Port


class SubmersiblePump(Pump):
    """Submersible (sump) pump: it stands in the liquid it pumps.

    The suction is the strainer plate it sits on rather than a piped nozzle, so
    the drawing is piped from underneath; the discharge is the riser out of the
    casing.
    """

    kind = "pump"
    VARIANTS = ("default", "submersible")
    VARIANT_ALIASES = {"default": "submersible"}
    PORTS = [("suction", "inlet", "process"), ("discharge", "outlet", "process")]

    suction: Port
    discharge: Port


class VacuumPump(Pump):
    """Vacuum pump: the machine that pulls a system below atmospheric.

    Drawn as a pump rather than as a compressor because that is the stencil the
    set files it under; a liquid-ring machine doing the same duty is
    :class:`LiquidRingCompressor`.
    """

    kind = "pump"
    VARIANTS = ("default", "vacuum")
    VARIANT_ALIASES = {"default": "vacuum"}
    PORTS = [("suction", "inlet", "process"), ("discharge", "outlet", "process")]

    suction: Port
    discharge: Port


class CentrifugalCompressor(Compressor):
    """Centrifugal compressor: dynamic compression, for large gas flows.

    What ``Compressor`` draws when it is asked for by name. Its stable range is
    bounded by surge at low flow, which is what the anti-surge recycle round one
    is for; a reciprocating machine has no such limit and needs no such line.
    """

    kind = "compressor"
    VARIANTS = ("default",)
    PORTS = [("suction", "inlet", "process"), ("discharge", "outlet", "process")]

    suction: Port
    discharge: Port


class ReciprocatingCompressor(Compressor):
    """Reciprocating compressor: positive displacement, for high ratio or low flow.

    A piston in a cylinder, so the discharge pulses and the ratio is set by
    geometry rather than by speed. Like every positive displacement machine it
    is protected by a relief valve on the discharge.
    """

    kind = "compressor"
    VARIANTS = ("default", "reciprocating")
    VARIANT_ALIASES = {"default": "reciprocating"}
    PORTS = [("suction", "inlet", "process"), ("discharge", "outlet", "process")]

    suction: Port
    discharge: Port


class RotaryCompressor(Compressor):
    """Rotary compressor: screws or lobes, positive displacement and oil-free duty.

    The plant-air and blower-service machine: steady flow, modest ratio, and no
    valves to pulse.
    """

    kind = "compressor"
    VARIANTS = ("default", "rotary")
    VARIANT_ALIASES = {"default": "rotary"}
    PORTS = [("suction", "inlet", "process"), ("discharge", "outlet", "process")]

    suction: Port
    discharge: Port


class LiquidRingCompressor(Compressor):
    """Liquid-ring compressor or vacuum pump: a rotating liquid seal does the work.

    Wet, tolerant of carryover and inherently cool, which is why it is the
    machine on a vacuum system handling condensable or dirty vapour. It carries
    a service liquid, which the sheet draws as an ordinary connection to the
    machine rather than as a nozzle of its own.
    """

    kind = "compressor"
    VARIANTS = ("default", "liquid_ring")
    VARIANT_ALIASES = {"default": "liquid_ring"}
    PORTS = [("suction", "inlet", "process"), ("discharge", "outlet", "process")]

    suction: Port
    discharge: Port


class ShellAndTubeExchanger(HeatExchanger):
    """Shell-and-tube exchanger: a tube bundle inside a shell.

    The default exchanger and the one most of the family's drawings are styles
    of: the ISO circle-and-zigzag (``default``, ``shell_tube``), the U-tube and
    hairpin bundles that turn round inside the shell (``u_tube``, ``hairpin``),
    the horizontal elevation a real sheet draws (``straight_tubes``) and the
    finned bundle in the same casing (``finned``).

    Nozzles are named for the **side of the equipment** they sit on, never for
    the duty the stream carries: which fluid runs in the shell and which in the
    tubes is a design decision worth recording, and hot and cold invert between
    operating cases while the nozzle stays where it is.
    """

    kind = "hex"
    VARIANTS = ("default", "shell_tube", "u_tube", "straight_tubes", "finned", "hairpin")
    PORTS = [
        ("shell_in", "inlet", "process"),
        ("shell_out", "outlet", "process"),
        ("tube_in", "inlet", "process"),
        ("tube_out", "outlet", "process"),
    ]

    shell_in: Port
    shell_out: Port
    tube_in: Port
    tube_out: Port


class DoublePipeExchanger(HeatExchanger):
    """Double-pipe exchanger: one pipe inside another, drawn as a hairpin.

    The small-duty exchanger, and the one whose two sides really are a tube and
    an annulus. Both fluids enter at the same end and turn round at the far one,
    so neither side has an east nozzle.
    """

    kind = "hex"
    VARIANTS = ("default", "double_pipe")
    VARIANT_ALIASES = {"default": "double_pipe"}
    PORTS = [
        ("shell_in", "inlet", "process"),
        ("shell_out", "outlet", "process"),
        ("tube_in", "inlet", "process"),
        ("tube_out", "outlet", "process"),
    ]

    shell_in: Port
    shell_out: Port
    tube_in: Port
    tube_out: Port


class KettleReboiler(HeatExchanger):
    """Kettle reboiler: a shell-and-tube bundle in an enlarged shell with a weir.

    The one exchanger with a nozzle more. ``bottoms`` is the draw at the weir
    end: what does not boil overflows the plate and leaves the bottom of the
    shell, which is where a tower's bottoms product physically gets off the
    sheet. The draw belongs on the exchanger, not on an invented splitter in the
    sump line.

    The heating medium is the **tube** side; the process boils in the shell. The
    stencil draws one channel-head opening, so ``tube_out`` takes the shell's far
    dished head.
    """

    kind = "hex"
    VARIANTS = ("default", "kettle")
    VARIANT_ALIASES = {"default": "kettle"}
    PORTS = [
        ("shell_in", "inlet", "process"),
        ("shell_out", "outlet", "process"),
        ("tube_in", "inlet", "process"),
        ("tube_out", "outlet", "process"),
        ("bottoms", "outlet", "liquid"),
    ]

    shell_in: Port
    shell_out: Port
    tube_in: Port
    tube_out: Port
    bottoms: Port


class Condenser(HeatExchanger):
    """Condenser: the shell-and-tube exchanger that takes an overhead vapour to liquid.

    The circle-and-zigzag with the heat-removed arrow across it, so the sides
    read the same way as the rest of the shell-and-tube family. For the
    single-stream utility symbol, where the cooling medium is a connection
    rather than a side, reach for :class:`pandid.units.Cooler` instead.
    """

    kind = "hex"
    VARIANTS = ("default", "condenser")
    VARIANT_ALIASES = {"default": "condenser"}
    PORTS = [
        ("shell_in", "inlet", "process"),
        ("shell_out", "outlet", "process"),
        ("tube_in", "inlet", "process"),
        ("tube_out", "outlet", "process"),
    ]

    shell_in: Port
    shell_out: Port
    tube_in: Port
    tube_out: Port


class AirCooledExchanger(HeatExchanger):
    """Air-cooled (fin-fan) exchanger: a finned tube bundle with air blown over it.

    The only piped side is the tube bundle. There is no shell, so the nozzles
    say so: ``air_in`` and ``air_out`` are the induced-draft bay's own faces,
    under the bundle and out through the fan, and neither is a pipe. That is
    why this is a class and not a style -- an exchanger with no shell cannot
    carry ``shell_in``.
    """

    kind = "hex"
    VARIANTS = ("default", "air_cooled")
    VARIANT_ALIASES = {"default": "air_cooled"}
    PORTS = [
        ("tube_in", "inlet", "process"),
        ("tube_out", "outlet", "process"),
        ("air_in", "inlet", "process"),
        ("air_out", "outlet", "process"),
    ]

    tube_in: Port
    tube_out: Port
    air_in: Port
    air_out: Port


class PlateExchanger(HeatExchanger):
    """Plate exchanger: a gasketed or brazed pack of plates, two circuits through it.

    Neither circuit is a shell or a tube and the two are physically
    interchangeable, so they are **lettered** rather than named: ``side_a`` and
    ``side_b``, each following the diagonal the artwork actually draws.
    """

    kind = "hex"
    VARIANTS = ("default", "plate")
    VARIANT_ALIASES = {"default": "plate"}
    PORTS = [
        ("side_a_in", "inlet", "process"),
        ("side_a_out", "outlet", "process"),
        ("side_b_in", "inlet", "process"),
        ("side_b_out", "outlet", "process"),
    ]

    side_a_in: Port
    side_a_out: Port
    side_b_in: Port
    side_b_out: Port


class SpiralExchanger(HeatExchanger):
    """Spiral exchanger: two channels coiled about a common centre.

    Lettered sides for :class:`PlateExchanger`'s reason: neither channel is a
    shell or a tube. The self-cleaning geometry is what puts one in fouling or
    slurry duty.
    """

    kind = "hex"
    VARIANTS = ("default", "spiral")
    VARIANT_ALIASES = {"default": "spiral"}
    PORTS = [
        ("side_a_in", "inlet", "process"),
        ("side_a_out", "outlet", "process"),
        ("side_b_in", "inlet", "process"),
        ("side_b_out", "outlet", "process"),
    ]

    side_a_in: Port
    side_a_out: Port
    side_b_in: Port
    side_b_out: Port


class ThinFilmEvaporator(HeatExchanger):
    """Thin-film (wiped-film) evaporator: a rotor spreads the feed on a heated wall.

    The one evaporator in the set, and the one exchanger whose two sides are a
    **jacket** and a **product** side. Product runs top to bottom -- onto the
    wiper at the top, concentrate out of the cone apex -- and the heating medium
    goes through the jacket, which is why neither pair borrows the shell-and-tube
    names.
    """

    kind = "hex"
    VARIANTS = ("default", "thin_film")
    VARIANT_ALIASES = {"default": "thin_film"}
    PORTS = [
        ("jacket_in", "inlet", "process"),
        ("jacket_out", "outlet", "process"),
        ("product_in", "inlet", "process"),
        ("product_out", "outlet", "process"),
    ]

    jacket_in: Port
    jacket_out: Port
    product_in: Port
    product_out: Port


class Cyclone(Separator):
    """Cyclone separator: a vortex throws the heavy phase to the wall and down the cone.

    The gas-solid workhorse -- off a spray dryer, a fluidised bed, a mill -- and
    the hydrocyclone in a classifying duty. ISO 15519-1 symbol X 2618, and one
    of the two the standard names as symbols gravity fixes the attitude of: the
    apex points down and the drawing says nothing true turned.

    The draws are ``overflow`` and ``underflow``, not ``vapor`` and ``liquid``:
    what leaves the apex is a catch, and calling a hopper full of dust a liquid
    is the bend this class exists to stop. ``Separator(variant="cyclone")``
    draws the same pair as of 0.1.2; see the module docstring.
    """

    kind = "separator"
    VARIANTS = ("default", "cyclone")
    VARIANT_ALIASES = {"default": "cyclone"}
    PORTS = [
        ("feed", "inlet", "feed"),
        ("overflow", "outlet", "process"),
        ("underflow", "outlet", "process"),
    ]

    feed: Port
    overflow: Port
    underflow: Port


class GravitySeparator(Separator):
    """Gravity separator (settling chamber): velocity drops and the heavy phase falls out.

    The crudest gas-solid separator there is, and usually the first stage ahead
    of a cyclone or a filter. ``overflow`` and ``underflow`` for
    :class:`Cyclone`'s reason.
    """

    kind = "separator"
    VARIANTS = ("default", "gravity")
    VARIANT_ALIASES = {"default": "gravity"}
    PORTS = [
        ("feed", "inlet", "feed"),
        ("overflow", "outlet", "process"),
        ("underflow", "outlet", "process"),
    ]

    feed: Port
    overflow: Port
    underflow: Port


class ElectrostaticPrecipitator(Separator):
    """Electrostatic precipitator: charged particles migrate to a collecting plate.

    The high-efficiency dust collector on a flue-gas or a kiln duty, rapped
    clear into the hopper below. ``overflow`` and ``underflow`` for
    :class:`Cyclone`'s reason.
    """

    kind = "separator"
    VARIANTS = ("default", "electrostatic")
    VARIANT_ALIASES = {"default": "electrostatic"}
    PORTS = [
        ("feed", "inlet", "feed"),
        ("overflow", "outlet", "process"),
        ("underflow", "outlet", "process"),
    ]

    feed: Port
    overflow: Port
    underflow: Port


class Screen(Separator):
    """Screen: a deck that sorts a solid by size, the oversize over and the fines through.

    Named ``Screen`` rather than ``Sifter`` because that is the word a
    specification uses and the word an engineer searches for, and because the
    one drawing stands for both duties a screen is bought for: **scalping**,
    taking a little oversize off a lot of product, and **sizing**, cutting a feed
    into fractions. Which of the two draws is the product is a fact about the
    service and not about the machine, which is why the nozzles name the two
    positions and not the contents.
    """

    kind = "separator"
    VARIANTS = ("default", "sifter")
    VARIANT_ALIASES = {"default": "sifter"}
    PORTS = [
        ("feed", "inlet", "feed"),
        ("overflow", "outlet", "process"),
        ("underflow", "outlet", "process"),
    ]

    feed: Port
    overflow: Port
    underflow: Port


class ImpactSeparator(Separator):
    """Impact separator: a baffle the stream is thrown at, so inertia does the sorting.

    The knock-out on a pneumatic conveying line or a vent, where the heavy
    fraction cannot follow the gas round the baffle.
    """

    kind = "separator"
    VARIANTS = ("default", "impact")
    VARIANT_ALIASES = {"default": "impact"}
    PORTS = [
        ("feed", "inlet", "feed"),
        ("overflow", "outlet", "process"),
        ("underflow", "outlet", "process"),
    ]

    feed: Port
    overflow: Port
    underflow: Port


class MagneticSeparator(Separator):
    """Magnetic separator: tramp metal pulled out of a solids stream.

    One class over both drawings, because the choice between a **permanent**
    magnet (``default``) and an **electromagnet** (``electromagnetic``) is a
    matter of how the field is made, not of what the machine does or of how it
    is piped: same body, same hopper, same two draws.
    """

    kind = "separator"
    VARIANTS = ("default", "electromagnetic", "permanent_magnet")
    VARIANT_ALIASES = {"default": "permanent_magnet"}
    PORTS = [
        ("feed", "inlet", "feed"),
        ("overflow", "outlet", "process"),
        ("underflow", "outlet", "process"),
    ]

    feed: Port
    overflow: Port
    underflow: Port


class Scrubber(Separator):
    """Wet scrubber: a wash liquid takes the contaminant out of a gas.

    Cleaned gas off the side, dirty scrubbing liquid out of the hopper, which
    really is a vapour and a liquid -- so unlike the collectors above this one
    keeps ``vapor`` and ``liquid``. A scrubber cleans a gas rather than
    classifying a solid.
    """

    kind = "separator"
    VARIANTS = ("default", "scrubber")
    VARIANT_ALIASES = {"default": "scrubber"}
    PORTS = [
        ("feed", "inlet", "feed"),
        ("vapor", "outlet", "vapor"),
        ("liquid", "outlet", "liquid"),
    ]

    feed: Port
    vapor: Port
    liquid: Port


class KnockoutDrum(Separator):
    """Knock-out drum: a vertical drum with a demister pad, ahead of a compressor or a flare.

    A mesh pad and a level gauge are both *drawn internals*, which the rule
    calls a variant -- and this is one of the two places the rule is
    deliberately overruled, because "knock-out drum" is the term a P&ID, a
    datasheet and a search box all use, and a class nobody can find is worth
    nothing. It is therefore near enough a duplicate of ``Separator``, and that
    is accepted.

    The gauge is *drawn*, not declared, so a level instrument added with
    :meth:`~pandid.flowsheet.Flowsheet.add_instrument` puts its own ISA-5.1
    balloon beside it and the sheet says the level is measured twice.
    """

    kind = "separator"
    VARIANTS = ("default", "knockout")
    VARIANT_ALIASES = {"default": "knockout"}
    PORTS = [
        ("feed", "inlet", "feed"),
        ("vapor", "outlet", "vapor"),
        ("liquid", "outlet", "liquid"),
    ]

    feed: Port
    vapor: Port
    liquid: Port


class DustCollector(Filter):
    """Dust collector: a gas filter with a hopper under the medium.

    One class over the three gas casings the stencil set draws -- bag, candle or
    cartridge elements (``default``), a granular bed (``fixed_bed``) and a cloth
    on rollers (``belt``) -- because choosing between them is a statement about
    the **medium**, which is what a variant is for, and all three are piped
    alike.

    Not called ``Baghouse``. That is the commonest member and the word most
    often reached for, but the same stencil stands for candle and cartridge
    filters, and a class named for one of the three would be wrong about the
    other two. The term is here in the docstring so a search finds it.
    """

    kind = "filter"
    VARIANTS = ("default", "fixed_bed", "belt", "gas", "gas_fixed_bed", "gas_belt")
    VARIANT_ALIASES = {"default": "gas", "fixed_bed": "gas_fixed_bed", "belt": "gas_belt"}
    PORTS = [("inlet", "inlet", "process"), ("outlet", "outlet", "process")]

    inlet: Port
    outlet: Port


class RotaryDrumFilter(Filter):
    """Rotary drum (or disc) filter: a drum turns through the slurry under vacuum.

    Cake builds on the submerged face and is lifted off at the top. The
    ``scraper`` variant is the same drum with the knife that lifts the cake
    drawn on it, which is the whole of the difference between the two shapes.
    """

    kind = "filter"
    VARIANTS = ("default", "scraper", "rotary", "rotary_scraper")
    VARIANT_ALIASES = {"default": "rotary", "scraper": "rotary_scraper"}
    PORTS = [("inlet", "inlet", "process"), ("outlet", "outlet", "process")]

    inlet: Port
    outlet: Port


class FilterPress(Filter):
    """Filter press: a pack of plates squeezed together, filtrate out and cake retained.

    A batch machine on a continuous sheet, which is exactly why it is worth its
    own row on an equipment list.
    """

    kind = "filter"
    VARIANTS = ("default", "press")
    VARIANT_ALIASES = {"default": "press"}
    PORTS = [("inlet", "inlet", "process"), ("outlet", "outlet", "process")]

    inlet: Port
    outlet: Port


class IonExchanger(Filter):
    """Ion exchanger: a resin bed between two retention screens.

    The vessel every demineraliser or softener train is drawn with. A filter by
    drawing and by piping; what it removes is dissolved rather than suspended.
    """

    kind = "filter"
    VARIANTS = ("default", "ion_exchange")
    VARIANT_ALIASES = {"default": "ion_exchange"}
    PORTS = [("inlet", "inlet", "process"), ("outlet", "outlet", "process")]

    inlet: Port
    outlet: Port


class RotaryDryer(Dryer):
    """Rotary drum (tumbling) dryer: a turning drum with hot gas through it.

    The bulk-solids dryer, and what ``Dryer`` draws when it is asked for by
    name.
    """

    kind = "dryer"
    VARIANTS = ("default",)
    PORTS = [("feed", "inlet", "feed"), ("product", "outlet", "process")]

    feed: Port
    product: Port


class FluidizedBedDryer(Dryer):
    """Fluidised-bed dryer: gas up through a distributor holds the solids in suspension.

    Even temperature and a high transfer rate, at the price of a bed that has to
    stay fluidised. The bed is a layer on its plate, so the symbol is one gravity
    fixes the attitude of.
    """

    kind = "dryer"
    VARIANTS = ("default", "fluidized_bed")
    VARIANT_ALIASES = {"default": "fluidized_bed"}
    PORTS = [("feed", "inlet", "feed"), ("product", "outlet", "process")]

    feed: Port
    product: Port


class SprayDryer(Dryer):
    """Spray dryer: a feed atomised into a hot gas, powder out of the floor.

    Fed through the atomiser in its roof and drawn top to bottom rather than
    across, which is why the artwork must not be turned. The cyclone downstream
    of one is where the product is usually recovered; see :class:`Cyclone`.
    """

    kind = "dryer"
    VARIANTS = ("default", "spray")
    VARIANT_ALIASES = {"default": "spray"}
    PORTS = [("feed", "inlet", "feed"), ("product", "outlet", "process")]

    feed: Port
    product: Port


class ControlValve(Valve):
    """Control valve: the final element a loop's output lands on.

    The valve a controller modulates: a diaphragm actuator over the body
    (``pneumatic``, ``butterfly_pneumatic``) or the Saunders body the set files
    under ``control``. It is the one valve family that regularly declares
    ``fail=``, where it goes when its air is lost, and it may **not** be shown
    normally closed -- PIP PIC001 clause 4.2.2.10, because a darkened control
    valve on an issued sheet reads as a block valve someone has closed. Say
    ``fail="closed"`` instead.
    """

    kind = "valve"
    VARIANTS = ("default", "pneumatic", "butterfly_pneumatic", "control")
    VARIANT_ALIASES = {"default": "control"}
    PORTS = [
        ("inlet", "inlet", "process"),
        ("outlet", "outlet", "process"),
        ("actuator", "inlet", "signal"),
    ]

    inlet: Port
    outlet: Port
    actuator: Port


class SolenoidValve(Valve):
    """Solenoid valve: an electrically operated on/off valve.

    The valve a trip acts through, and the pilot on a larger actuator. On/off
    rather than modulating, so it takes a ``fail`` position and it may be shown
    normally closed, which is how a dump or a purge valve is drawn.
    """

    kind = "valve"
    VARIANTS = ("default", "solenoid")
    VARIANT_ALIASES = {"default": "solenoid"}
    PORTS = [
        ("inlet", "inlet", "process"),
        ("outlet", "outlet", "process"),
        ("actuator", "inlet", "signal"),
    ]

    inlet: Port
    outlet: Port
    actuator: Port


class ReliefValve(Valve):
    """Pressure relief valve: it opens on its own when the set pressure is reached.

    The PSV/PRV a protected system is drawn with, in either of the two bodies
    the stencil set draws (``default`` is the bonnet-on-a-stem relief; ``psv``
    is the spring-loaded angle body a real sheet draws). Worked by the process
    itself, so it has no actuating energy to lose and declares no ``fail``, and
    PIP PIC001 4.2.2.10 forbids showing it normally closed.
    """

    kind = "valve"
    VARIANTS = ("default", "psv", "relief")
    VARIANT_ALIASES = {"default": "relief"}
    PORTS = [
        ("inlet", "inlet", "process"),
        ("outlet", "outlet", "process"),
        ("actuator", "inlet", "signal"),
    ]

    inlet: Port
    outlet: Port
    actuator: Port


class PressureRegulator(Valve):
    """Self-acting pressure regulator: the process works its own diaphragm.

    A back-pressure or a reducing regulator, holding a pressure with no
    controller and no signal. Its "actuator" connection is the external pilot
    line rather than a signal terminus. No ``fail`` position for
    :class:`ReliefValve`'s reason, and no NC mark for the same clause.
    """

    kind = "valve"
    VARIANTS = ("default", "regulator")
    VARIANT_ALIASES = {"default": "regulator"}
    PORTS = [
        ("inlet", "inlet", "process"),
        ("outlet", "outlet", "process"),
        ("actuator", "inlet", "signal"),
    ]

    inlet: Port
    outlet: Port
    actuator: Port


class MotorOperatedValve(Valve):
    """Motor-operated valve (MOV): a block valve driven by an electric actuator.

    Stroked open or shut from the control system rather than modulated, which is
    why it takes a ``fail`` position and, unlike a control valve, may be shown
    normally closed.
    """

    kind = "valve"
    VARIANTS = ("default", "motor")
    VARIANT_ALIASES = {"default": "motor"}
    PORTS = [
        ("inlet", "inlet", "process"),
        ("outlet", "outlet", "process"),
        ("actuator", "inlet", "signal"),
    ]

    inlet: Port
    outlet: Port
    actuator: Port


class CheckValve(Valve):
    """Check valve: it passes flow one way and shuts against the other.

    Worked by the flow itself. **It has no actuator**, so this class does not
    declare one: a check valve is not something a controller output can land on,
    and a signal line drawn to one is a mistake worth refusing rather than
    drawing. That missing nozzle is the whole reason this is a class and not a
    body style.

    Its arrow lives inside the outline and would be swallowed by a darkened
    body, so a normally closed one draws the letters ``NC`` beside it instead
    (PIP PIC001 clause 4.2.2.8).
    """

    kind = "valve"
    VARIANTS = ("default", "check")
    VARIANT_ALIASES = {"default": "check"}
    PORTS = [("inlet", "inlet", "process"), ("outlet", "outlet", "process")]

    inlet: Port
    outlet: Port


class SpectacleBlind(Fitting):
    """Spectacle blind (figure-8 blind): two discs on a tie, one bored and one solid.

    The one fitting with a **declarable property**, which is what makes it a
    class. Which disc is in the line is the whole of what the symbol says, and
    the stencil set draws both states:

    - ``normal_position="open"`` (the default) puts the **ring** in the line,
      with the solid disc parked above it: the line is through.
    - ``normal_position="closed"`` puts the **solid** disc in the line: blanked.

    A change of shape, not a mark added to one, so a blind is never shown in a
    position by inference.
    """

    kind = "fitting"
    VARIANTS = ("default", "blind")
    VARIANT_ALIASES = {"default": "blind"}
    PORTS = [("inlet", "inlet", "process"), ("outlet", "outlet", "process")]

    inlet: Port
    outlet: Port


class FlowElement(Fitting):
    """Primary flow element: the device in the run an FE balloon reads.

    One class over the twelve the stencil set draws, because to the flowsheet
    they are the same thing -- a pair of faces on a line -- and the choice
    between them is the metering principle: a differential-pressure profile
    (``default``/``venturi``, ``flow_nozzle``, ``v_cone``, ``wedge``, ``target``,
    ``pitot``, ``averaging_pitot``) or a meter body (``coriolis``, ``vortex``,
    ``ultrasonic``, ``turbine_meter``, ``positive_displacement``).

    It is a class rather than a style of ``Fitting`` because it is what an
    equipment or instrument schedule lists, which is the whole argument for the
    layer: a strainer and a venturi are the same shape of thing to the drawing
    and different rows on the list.

    Hang the balloon on one with
    :meth:`~pandid.flowsheet.Flowsheet.add_instrument`. The restriction orifice
    and the rotameter are **not** here: the first restricts rather than measures,
    and the second carries its own indication, so both stay
    ``Fitting`` variants where the class docstring already lists them.
    """

    kind = "fitting"
    VARIANTS = (
        "default",
        "venturi",
        "flow_nozzle",
        "coriolis",
        "vortex",
        "ultrasonic",
        "turbine_meter",
        "positive_displacement",
        "v_cone",
        "wedge",
        "target",
        "pitot",
        "averaging_pitot",
    )
    VARIANT_ALIASES = {"default": "venturi"}
    PORTS = [("inlet", "inlet", "process"), ("outlet", "outlet", "process")]

    inlet: Port
    outlet: Port


class StirredTankReactor(Reactor):
    """Stirred-tank reactor (CSTR): a charge vessel with a top-entering agitator.

    An agitator is a *drawn internal*, which the rule calls a variant -- and
    this is the second of the two places the rule is deliberately overruled, for
    :class:`KnockoutDrum`'s reason: "stirred tank reactor" and "CSTR" are what a
    process engineer searches for, and it is what ``Reactor`` already draws when
    it is asked for by name. A near-duplicate of its base, accepted.

    ``n_feeds`` gives the vessel more than one charge nozzle, exactly as it does
    on :class:`pandid.units.Reactor`.
    """

    kind = "reactor"
    VARIANTS = ("default",)
    PORTS = [
        ("outlet", "outlet", "process"),
        ("vent", "outlet", "vapor"),
        ("duty", "inlet", "energy"),
    ]

    outlet: Port
    vent: Port
    duty: Port
